/**
 * validate-earth-export.ts - validates Azgaar's full JSON export for Earth-like geography.
 *
 * Usage:
 *   npm run worldgen:validate
 *   npm run worldgen:validate -- --input macro-world/earth-reference/azgaar-export.json
 *
 * The export is generated by Azgaar Fantasy Map Generator. This script checks for
 * recognizable Earth-scale signals before later worldgen steps depend on the file.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const DEFAULT_EXPORT_PATH = path.join(
  REPO_ROOT,
  'macro-world',
  'earth-reference',
  'azgaar-export.json',
);

const MIN_CELL_COUNT = 5_000;
const MAX_CELL_COUNT = 100_000;
const LAND_HEIGHT_THRESHOLD = 20;
const MIN_LAND_RATIO = 0.2;
const MAX_LAND_RATIO = 0.4;
const MIN_BIOME_TYPES = 6;
const MIN_RIVERS = 10;
const MIN_MAJOR_LANDMASSES = 4;
const MAX_MAJOR_LANDMASSES = 8;
const MIN_MAJOR_LANDMASS_CELLS = 20;

type Point = [number, number];

interface ParsedArgs {
  inputPath: string;
}

interface AzgaarExport {
  pack: {
    cells: {
      h: number[];
      biome: number[];
      c: number[][];
      g: number[];
      p?: Point[];
    };
    rivers?: unknown[];
  };
  grid: {
    cells: {
      temp: number[];
      p?: Point[];
    };
  };
}

interface ValidationResult {
  label: string;
  value: string;
  ok: boolean;
  expectation: string;
}

interface TemperatureSummary {
  polarAverage: number;
  equatorAverage: number;
}

function parseArgs(): ParsedArgs {
  const args = process.argv.slice(2);
  let inputPath = DEFAULT_EXPORT_PATH;

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    if (arg === '--input' && args[i + 1]) {
      inputPath = path.resolve(args[++i]);
    } else if (arg === '--help' || arg === '-h') {
      console.log('Usage: npm run worldgen:validate -- --input <azgaar-export.json>');
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return { inputPath };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function getRecord(value: Record<string, unknown>, key: string): Record<string, unknown> {
  const child = value[key];
  if (!isRecord(child)) {
    throw new Error(`Export is missing object: ${key}`);
  }

  return child;
}

function getNumberArray(value: Record<string, unknown>, key: string): number[] {
  const child = value[key];
  if (!Array.isArray(child) || !child.every((item) => typeof item === 'number')) {
    throw new Error(`Export is missing numeric array: ${key}`);
  }

  return child;
}

function getNeighborArray(value: Record<string, unknown>, key: string): number[][] {
  const child = value[key];
  if (
    !Array.isArray(child) ||
    !child.every(
      (neighbors) =>
        Array.isArray(neighbors) && neighbors.every((item) => typeof item === 'number'),
    )
  ) {
    throw new Error(`Export is missing neighbor array: ${key}`);
  }

  return child;
}

function getOptionalPointArray(value: Record<string, unknown>, key: string): Point[] | undefined {
  const child = value[key];
  if (child === undefined) {
    return undefined;
  }

  if (
    !Array.isArray(child) ||
    !child.every(
      (point) =>
        Array.isArray(point) &&
        point.length >= 2 &&
        typeof point[0] === 'number' &&
        typeof point[1] === 'number',
    )
  ) {
    throw new Error(`Export has invalid point array: ${key}`);
  }

  return child.map((point) => [point[0], point[1]]);
}

function parseAzgaarExport(rawJson: string): AzgaarExport {
  const parsed: unknown = JSON.parse(rawJson) as unknown;
  if (!isRecord(parsed)) {
    throw new Error('Export root must be a JSON object');
  }

  const pack = getRecord(parsed, 'pack');
  const packCells = getRecord(pack, 'cells');
  const grid = getRecord(parsed, 'grid');
  const gridCells = getRecord(grid, 'cells');

  const heights = getNumberArray(packCells, 'h');
  const biomes = getNumberArray(packCells, 'biome');
  const neighbors = getNeighborArray(packCells, 'c');
  const gridRefs = getNumberArray(packCells, 'g');
  const temperatures = getNumberArray(gridCells, 'temp');
  const packPoints = getOptionalPointArray(packCells, 'p');
  const gridPoints = getOptionalPointArray(gridCells, 'p');
  const rivers = Array.isArray(pack.rivers) ? pack.rivers : undefined;

  validateCellArrayLengths(heights.length, [
    ['pack.cells.biome', biomes.length],
    ['pack.cells.c', neighbors.length],
    ['pack.cells.g', gridRefs.length],
  ]);

  if (packPoints !== undefined && packPoints.length < heights.length) {
    throw new Error('pack.cells.p must have at least one point per pack cell');
  }

  return {
    pack: {
      cells: {
        h: heights,
        biome: biomes,
        c: neighbors,
        g: gridRefs,
        p: packPoints,
      },
      rivers,
    },
    grid: {
      cells: {
        temp: temperatures,
        p: gridPoints,
      },
    },
  };
}

function validateCellArrayLengths(cellCount: number, arrays: Array<[string, number]>): void {
  for (const [name, length] of arrays) {
    if (length < cellCount) {
      throw new Error(`${name} has ${length} entries, expected at least ${cellCount}`);
    }
  }
}

function countLandCells(heights: number[]): number {
  return heights.filter((height) => height >= LAND_HEIGHT_THRESHOLD).length;
}

function countBiomeTypes(biomes: number[]): number {
  return new Set(biomes.filter((biome) => Number.isFinite(biome))).size;
}

function countMajorLandmasses(heights: number[], neighbors: number[][]): number {
  const landCells = new Set<number>();

  for (let i = 0; i < heights.length; i++) {
    if (heights[i] >= LAND_HEIGHT_THRESHOLD) {
      landCells.add(i);
    }
  }

  const visited = new Set<number>();
  const landmassSizes: number[] = [];

  for (const startCell of landCells) {
    if (visited.has(startCell)) {
      continue;
    }

    const size = floodFillLandmass(startCell, landCells, neighbors, visited);
    landmassSizes.push(size);
  }

  return landmassSizes.filter((size) => size >= MIN_MAJOR_LANDMASS_CELLS).length;
}

function floodFillLandmass(
  startCell: number,
  landCells: Set<number>,
  neighbors: number[][],
  visited: Set<number>,
): number {
  const queue: number[] = [startCell];
  visited.add(startCell);
  let size = 0;

  while (queue.length > 0) {
    const cell = queue.shift();
    if (cell === undefined) {
      continue;
    }

    size++;

    for (const neighbor of neighbors[cell] ?? []) {
      if (
        Number.isInteger(neighbor) &&
        landCells.has(neighbor) &&
        !visited.has(neighbor)
      ) {
        visited.add(neighbor);
        queue.push(neighbor);
      }
    }
  }

  return size;
}

function summarizeTemperatureGradient(exportData: AzgaarExport): TemperatureSummary {
  const samples = collectTemperatureSamples(exportData);
  if (samples.length === 0) {
    throw new Error('No valid temperature samples found via pack.cells.g -> grid.cells.temp');
  }

  const yValues = samples.map((sample) => sample.y);
  const minY = Math.min(...yValues);
  const maxY = Math.max(...yValues);
  const rangeY = maxY - minY;

  if (rangeY <= 0) {
    throw new Error('Cell coordinates do not span multiple latitude bands');
  }

  const polarCutoff = rangeY * 0.2;
  const equatorMin = minY + rangeY * 0.4;
  const equatorMax = minY + rangeY * 0.6;

  const polarSamples = samples.filter(
    (sample) => sample.y <= minY + polarCutoff || sample.y >= maxY - polarCutoff,
  );
  const equatorSamples = samples.filter(
    (sample) => sample.y >= equatorMin && sample.y <= equatorMax,
  );

  if (polarSamples.length === 0 || equatorSamples.length === 0) {
    throw new Error('Not enough cell coordinates to compare polar and equatorial bands');
  }

  return {
    polarAverage: average(polarSamples.map((sample) => sample.temperature)),
    equatorAverage: average(equatorSamples.map((sample) => sample.temperature)),
  };
}

function collectTemperatureSamples(
  exportData: AzgaarExport,
): Array<{ y: number; temperature: number }> {
  const { g: gridRefs, p: packPoints } = exportData.pack.cells;
  const { temp: temperatures, p: gridPoints } = exportData.grid.cells;
  const samples: Array<{ y: number; temperature: number }> = [];

  for (let cellId = 0; cellId < gridRefs.length; cellId++) {
    const gridCellId = gridRefs[cellId];
    if (!Number.isInteger(gridCellId)) {
      continue;
    }

    const temperature = temperatures[gridCellId];
    if (temperature === undefined || !Number.isFinite(temperature)) {
      continue;
    }

    const point = gridPoints?.[gridCellId] ?? packPoints?.[cellId];
    if (point === undefined) {
      continue;
    }

    samples.push({ y: point[1], temperature });
  }

  return samples;
}

function average(values: number[]): number {
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function buildValidationResults(exportData: AzgaarExport): ValidationResult[] {
  const cellCount = exportData.pack.cells.h.length;
  const landCells = countLandCells(exportData.pack.cells.h);
  const landRatio = landCells / cellCount;
  const biomeTypes = countBiomeTypes(exportData.pack.cells.biome);
  const riverCount = exportData.pack.rivers?.length ?? 0;
  const majorLandmasses = countMajorLandmasses(
    exportData.pack.cells.h,
    exportData.pack.cells.c,
  );
  const temperature = summarizeTemperatureGradient(exportData);

  return [
    {
      label: 'Cell count',
      value: cellCount.toLocaleString('en-US'),
      ok: cellCount >= MIN_CELL_COUNT && cellCount <= MAX_CELL_COUNT,
      expectation: '5k-100k',
    },
    {
      label: 'Land ratio',
      value: `${(landRatio * 100).toFixed(1)}%`,
      ok: landRatio >= MIN_LAND_RATIO && landRatio <= MAX_LAND_RATIO,
      expectation: '20-40%',
    },
    {
      label: 'Biome types',
      value: `${biomeTypes}/12`,
      ok: biomeTypes >= MIN_BIOME_TYPES,
      expectation: '>=6',
    },
    {
      label: 'Rivers',
      value: riverCount.toLocaleString('en-US'),
      ok: riverCount >= MIN_RIVERS,
      expectation: '>=10',
    },
    {
      label: 'Major landmasses',
      value: majorLandmasses.toLocaleString('en-US'),
      ok:
        majorLandmasses >= MIN_MAJOR_LANDMASSES &&
        majorLandmasses <= MAX_MAJOR_LANDMASSES,
      expectation: '4-8',
    },
    {
      label: 'Temp gradient',
      value: `${temperature.polarAverage.toFixed(1)}C -> ${temperature.equatorAverage.toFixed(
        1,
      )}C`,
      ok: temperature.polarAverage < temperature.equatorAverage,
      expectation: 'polar < equator',
    },
  ];
}

function renderReport(results: ValidationResult[]): string {
  const lines = ['Earth Export Validation', '======================='];

  for (const result of results) {
    const status = result.ok ? 'PASS' : 'FAIL';
    lines.push(
      `${`${result.label}:`.padEnd(18)} ${result.value.padEnd(14)} ${status} (${result.expectation})`,
    );
  }

  return lines.join('\n');
}

async function main(): Promise<void> {
  try {
    const { inputPath } = parseArgs();

    if (!fs.existsSync(inputPath)) {
      throw new Error(`Export file not found: ${inputPath}`);
    }

    const rawJson = await fs.promises.readFile(inputPath, 'utf8');
    const exportData = parseAzgaarExport(rawJson);
    const results = buildValidationResults(exportData);

    console.log(renderReport(results));

    if (results.some((result) => !result.ok)) {
      process.exit(1);
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`Earth export validation failed: ${message}`);
    process.exit(1);
  }
}

void main();
