/**
 * CombatEngineer — Loke at Tier 3, post-promotion.
 *
 * ## Narrative context
 *
 * The same Loke who scouted as Tinkerer (T2) has graduated to the Combat
 * Engineer role: field operator, gadget specialist, forward-deployed builder.
 * Older, harder, and carrying a lot more kit. His pistol is gone; the M12
 * Carbine and a full deployable kit replace it. The exo-frame makes him slower
 * but significantly harder to put down.
 *
 * ## What's implemented here (Child A — scaffolding)
 *
 * - Class skeleton extending EarthHero with Tier-3 stats
 * - `useSignature()` stub — logs and no-ops until Child C wires the deployable system
 * - Behaviour tree: mirrors Tinkerer's tree (escape → ranged → melee → chase)
 *   since the Carbine and deployable bindings land in Children C/D
 * - Placeholder sprite key (`combat-engineer`) — missing-animation warnings are
 *   acceptable at this stage
 * - `designNotes` for the sprite-credit-burn agent
 *
 * ## What is NOT here yet
 *
 * - M12 Carbine burst-fire mechanic (Child D)
 * - Deployable system (Children B/C)
 * - Deployable HUD (Child D)
 * - Q/E/R/F keybindings (Child C)
 * - Real sprite and animations (PixelLab generation via sprite-credit-burn)
 *
 * ## Stats rationale
 *
 * Tinkerer (T2): HP 100, speed 80 — fast glass-cannon pistol-fighter.
 * CombatEngineer (T3): HP 130, speed 68, damageReduction 0.88 — tanky operator.
 * The exo-frame trades agility for survivability and loadout capacity.
 */

import * as Phaser from 'phaser';
import {
  BtNode,
  BtSelector,
  BtSequence,
  BtCondition,
  BtAction,
  BtCooldown,
} from '../ai/BehaviorTree';
import { EarthHero } from './EarthHero';

// ── Tier stats ────────────────────────────────────────────────────────────────

/** Hit-points — exo-frame raises baseline vs Tinkerer's 100. */
const MAX_HP       = 130;
/** px/s — slower than Tinkerer (80) due to heavier kit. */
const SPEED        = 68;
/** Incoming damage multiplier. 0.88 = 12% flat reduction from exo-frame padding. */
const DMG_REDUCE   = 0.88;

// ── Carbine placeholder stats (Child D will refine to burst-fire) ─────────────

/** Damage per shot (placeholder; Carbine burst mechanic comes in Child D). */
const PROJ_DAMAGE  = 6;
/** Projectile speed px/s — slightly slower than Tinkerer's 420 (heavier round). */
const PROJ_SPEED   = 380;
/** Tracer colour — warm amber to distinguish from Tinkerer's pale yellow. */
const PROJ_COLOR   = 0xff9944;

// ── Behaviour tree tuning ─────────────────────────────────────────────────────

const MELEE_R    = 32;   // px — matches meleeRange below
const DASH_MIN   = MELEE_R;
const DASH_MAX   = 280;
const RANGED_MIN = 60;
const RANGED_MAX = 210;  // slightly shorter than Tinkerer's 230 (Carbine is close-mid)
const SWARM_R    = 120;
const SWARM_CAP  = 4;

/**
 * CombatEngineer — Loke at Tier 3. EarthHero subclass with deployable-oriented
 * kit. Most abilities are stubs pending Children B/C/D.
 *
 * Sprite: 'combat-engineer' (not yet generated — missing-anim warnings expected).
 *
 * designNotes (for sprite-credit-burn agent):
 *   "Loke as T3 Combat Engineer. Same facial features and ash-blond hair as
 *    Tinkerer-Loke, now older and harder. Milspec operator kit: olive-drab
 *    webbing vest, exo-frame reinforcement at shoulders and knees, M12 carbine
 *    held low-ready, utility pouches on belt, flip-up HUD visor on helmet.
 *    32×32 top-down pixel art. Matches the Tinkerer-Loke colour palette —
 *    swap canvas jacket for exo-frame plating, keep face and hair identical."
 */
export class CombatEngineer extends EarthHero {
  /** Human-readable name used in HUD labels and log output. */
  readonly name = 'CombatEngineer';

  /**
   * Signature ability cooldown.
   * Longer than Tinkerer (8 s) — the Engineer's signature will be a powerful
   * deployable-overcharge rather than a simple dash (Child C).
   */
  readonly signatureCooldownMs = 12_000;

  constructor(scene: Phaser.Scene, x: number, y: number) {
    super(scene, x, y, {
      maxHp:              MAX_HP,
      speed:              SPEED,
      aggroRadius:        380,
      proximityRadius:    220,
      attackDamage:       14,     // melee punch — decent but not the primary tool
      color:              0x556b2f,  // olive-drab placeholder rect
      meleeRange:         MELEE_R,
      attackCooldownMs:   800,
      projectileDamage:   PROJ_DAMAGE,
      projectileSpeed:    PROJ_SPEED,
      projectileColor:    PROJ_COLOR,
      dashSpeedMultiplier: 4.0,    // shorter dash than Tinkerer's 5× (heavier kit)
      dashDurationMs:     220,
      // No sprite yet — the entity will render as an olive-drab rectangle.
      // Once 'combat-engineer' is generated by PixelLab and assembled, set this:
      //   spriteKey: 'combat-engineer',
    });

    // Tier tag — used by tier-aware UI (arena select, HUD tier badge).
    this.setData('tier', 3);

    // Exo-frame passive: 12% flat incoming damage reduction.
    // Applied before any other multipliers via LivingEntity.damageReduction.
    this.damageReduction = DMG_REDUCE;
  }

  // ── Signature ability (stub) ──────────────────────────────────────────────────

  /**
   * Deployable Overcharge — triggers a boost mode that reduces all deploy
   * cooldowns to 0 and overclocks the Sentry Turret for 4 s.
   *
   * Stub: logs and returns until Child C wires the deployable system.
   * Player-input code may call this freely — the stub is a safe no-op.
   */
  useSignature(): void {
    // Stub — Deployable Overcharge not yet implemented (wired in Child C).
    console.log('[CombatEngineer] useSignature called — stub, no-op until Child C');
  }

  // ── Behaviour tree ────────────────────────────────────────────────────────────

  /**
   * AI behaviour tree for uncontrolled-hero mode.
   *
   * Mirrors the Tinkerer tree (escape dash → ranged → melee → gap-close → chase
   * → wander) without the mine-deploy node (deployable system is Child B/C).
   * Child D will extend this with Carbine burst-fire and deploy triggers.
   */
  protected buildTree(): BtNode {
    const swarmPressure = (cx: number, cy: number): number =>
      this.opponents.filter(
        o => o.isAlive &&
          Phaser.Math.Distance.Between(cx, cy, o.x, o.y) < SWARM_R,
      ).length;

    return new BtSelector([

      // 1. Escape dash when swarmed at low HP — back away from the crowd centroid.
      new BtCooldown(
        new BtSequence([
          new BtCondition(ctx =>
            swarmPressure(ctx.x, ctx.y) >= SWARM_CAP &&
            ctx.hp < ctx.maxHp * 0.7,    // slightly lower threshold than Tinkerer
          ),
          new BtAction(ctx => {
            const near = this.opponents.filter(
              o => o.isAlive &&
                Phaser.Math.Distance.Between(ctx.x, ctx.y, o.x, o.y) < SWARM_R,
            );
            const avgX = near.reduce((s, o) => s + o.x, 0) / near.length;
            const avgY = near.reduce((s, o) => s + o.y, 0) / near.length;
            ctx.dash(ctx.x + (ctx.x - avgX) * 3, ctx.y + (ctx.y - avgY) * 3);
            return 'success';
          }),
        ]),
        4000,
      ),

      // 2. Melee bash — only at close range and when not overwhelmed.
      new BtSequence([
        new BtCondition(ctx => {
          if (!ctx.opponent) return false;
          const d = Phaser.Math.Distance.Between(ctx.x, ctx.y, ctx.opponent.x, ctx.opponent.y);
          return d < MELEE_R && swarmPressure(ctx.x, ctx.y) < 3;
        }),
        new BtAction(ctx => {
          this.attackAnimId = 'attack_melee';
          ctx.attack();
          ctx.stop();
          return 'success';
        }),
      ]),

      // 3. Carbine (placeholder pistol-style until Child D burst-fire lands).
      new BtCooldown(
        new BtSequence([
          new BtCondition(ctx => {
            if (!ctx.opponent) return false;
            const d = Phaser.Math.Distance.Between(ctx.x, ctx.y, ctx.opponent.x, ctx.opponent.y);
            return d >= RANGED_MIN && d <= RANGED_MAX;
          }),
          new BtAction(ctx => {
            this.attackAnimId = 'attack_ranged';
            const shotAngle = Math.atan2(
              ctx.opponent!.y - ctx.y,
              ctx.opponent!.x - ctx.x,
            );
            ctx.shootAt(ctx.opponent!.x, ctx.opponent!.y);
            this.scene.events.emit('hero-shot', ctx.x, ctx.y, shotAngle);
            return 'success';
          }),
        ]),
        820,  // ms — slightly slower than Tinkerer burst to reflect single-shot placeholder
      ),

      // 4. Gap-close dash toward target.
      new BtCooldown(
        new BtSequence([
          new BtCondition(ctx => {
            if (!ctx.opponent) return false;
            const d = Phaser.Math.Distance.Between(ctx.x, ctx.y, ctx.opponent.x, ctx.opponent.y);
            return d > DASH_MIN && d < DASH_MAX;
          }),
          new BtAction(ctx => {
            ctx.dash(ctx.opponent!.x, ctx.opponent!.y);
            return 'success';
          }),
        ]),
        3000,
      ),

      // 5. Chase target.
      new BtSequence([
        new BtCondition(ctx => ctx.opponent !== null),
        new BtAction(ctx => {
          ctx.moveToward(ctx.opponent!.x, ctx.opponent!.y);
          return 'running';
        }),
      ]),

      // 6. Wander when no opponents visible.
      new BtAction((ctx, d) => { ctx.wander(d); return 'running'; }),
    ]);
  }
}
