/**
 * AssetViewerScene — manifest-driven browsable grid of all sprite assets.
 *
 * Loads sprite-manifest.json (generated by `npm run assets:sprites`) and
 * displays every PNG grouped by category. Each sprite shows a red ID number
 * and a green/red wired indicator.
 *
 * Route: /assets
 * Controls:
 *   Scroll / Arrow keys — scroll vertically
 *   Click sprite        — shows details (ID, key, size, path, wired status)
 *
 * To refresh after adding new assets: `npm run assets:sprites` then reload.
 */

import * as Phaser from 'phaser';

// ── Manifest types ──────────────────────────────────────────────────────────

interface ManifestAsset {
  name: string;
  url: string;
  folder: string;
  category: string;
  wired: boolean;
}

interface ManifestCategory {
  category: string;
  count: number;
  assets: ManifestAsset[];
}

interface SpriteManifest {
  totalAssets: number;
  wiredCount: number;
  unwiredCount: number;
  categories: ManifestCategory[];
}

// ── Scene ───────────────────────────────────────────────────────────────────

export class AssetViewerScene extends Phaser.Scene {
  static readonly KEY = 'AssetViewerScene';

  constructor() { super({ key: AssetViewerScene.KEY }); }

  private scrollY = 0;
  private contentHeight = 0;
  private container!: Phaser.GameObjects.Container;
  private detailText!: Phaser.GameObjects.Text;
  private manifest: SpriteManifest | null = null;

  preload(): void {
    this.load.json('sprite-manifest', '/assets/sprite-manifest.json');
  }

  create(): void {
    this.cameras.main.setBackgroundColor('#111118');
    this.manifest = this.cache.json.get('sprite-manifest') as SpriteManifest | null;

    if (!this.manifest) {
      this.add.text(400, 300,
        'No sprite-manifest.json found.\nRun: npm run assets:sprites', {
          fontSize: '16px', color: '#ff6666', align: 'center',
        }).setOrigin(0.5);
      return;
    }

    // Load all PNGs from the manifest
    for (const cat of this.manifest.categories) {
      for (const asset of cat.assets) {
        const key = `av-${asset.category}-${asset.name}`;
        if (!this.textures.exists(key)) {
          this.load.image(key, asset.url);
        }
      }
    }

    // Wait for all images to load, then build the grid
    this.load.once('complete', () => this.buildGrid());
    this.load.start();
  }

  private buildGrid(): void {
    if (!this.manifest) return;

    this.container = this.add.container(0, 0);

    const PAD = 12;
    const CELL = 72;
    const COLS = Math.floor((this.cameras.main.width - PAD * 2) / CELL);
    let y = 30;
    let globalIdx = 0;

    // Summary bar
    const summary = this.add.text(PAD, y,
      `${this.manifest.totalAssets} assets  |  ${this.manifest.wiredCount} wired  |  ${this.manifest.unwiredCount} unwired`, {
        fontSize: '11px', color: '#aaaaaa', backgroundColor: '#222233',
        padding: { x: 6, y: 3 },
      });
    this.container.add(summary);
    y += 28;

    for (const cat of this.manifest.categories) {
      // Section header
      const header = this.add.text(PAD, y,
        `${cat.category} (${cat.count})`, {
          fontSize: '13px', color: '#ffffff', fontStyle: 'bold',
          backgroundColor: '#222233', padding: { x: 6, y: 3 },
        });
      this.container.add(header);
      y += 26;

      let col = 0;
      for (const asset of cat.assets) {
        const texKey = `av-${asset.category}-${asset.name}`;
        if (!this.textures.exists(texKey)) continue;

        globalIdx++;
        const cx = PAD + col * CELL + CELL / 2;
        const cy = y + CELL / 2;

        // Cell background — green border if wired, red if not
        const borderColor = asset.wired ? 0x44aa44 : 0xaa4444;
        const bg = this.add.rectangle(cx, cy, CELL - 4, CELL - 4, 0x222233, 0.6)
          .setStrokeStyle(1, borderColor, 0.6);
        this.container.add(bg);

        // Sprite — fit to cell
        const img = this.add.image(cx, cy - 4, texKey);
        const maxDim = Math.max(img.width, img.height);
        const scale = maxDim > 0 ? Math.min((CELL - 16) / maxDim, 2.5) : 1;
        img.setScale(scale);
        this.container.add(img);

        // Red ID number (top-left)
        const idLabel = this.add.text(cx - CELL / 2 + 4, cy - CELL / 2 + 2,
          `${globalIdx}`, {
            fontSize: '8px', color: '#ff4444', fontStyle: 'bold',
            stroke: '#000000', strokeThickness: 2,
          });
        this.container.add(idLabel);

        // Wired indicator (top-right)
        const dot = this.add.circle(
          cx + CELL / 2 - 8, cy - CELL / 2 + 8, 4,
          asset.wired ? 0x44aa44 : 0xaa4444, 1,
        );
        this.container.add(dot);

        // Name label (bottom)
        const displayName = asset.name.length > 10
          ? asset.name.slice(0, 9) + '…'
          : asset.name;
        const label = this.add.text(cx, cy + CELL / 2 - 14, displayName, {
          fontSize: '7px', color: '#888888',
        }).setOrigin(0.5, 0);
        this.container.add(label);

        // Click for details
        bg.setInteractive();
        const thisIdx = globalIdx;
        bg.on('pointerdown', () => {
          const w = img.width, h = img.height;
          const status = asset.wired ? '✓ WIRED' : '✗ UNWIRED';
          this.detailText.setText(
            `#${thisIdx}  |  ${asset.name}  |  ${w}×${h}px  |  ${asset.url}  |  ${status}`,
          );
          this.detailText.setColor(asset.wired ? '#88ff88' : '#ff8888');
        });

        col++;
        if (col >= COLS) { col = 0; y += CELL; }
      }
      if (col > 0) y += CELL;
      y += 10;
    }

    this.contentHeight = y;

    // Detail bar (fixed bottom)
    this.detailText = this.add.text(
      this.cameras.main.width / 2, this.cameras.main.height - 8,
      'Click a sprite to see details  |  Green = wired  |  Red = unwired', {
        fontSize: '10px', color: '#888888', backgroundColor: '#000000cc',
        padding: { x: 10, y: 6 },
      },
    ).setOrigin(0.5, 1).setScrollFactor(0).setDepth(100);

    // Title
    this.add.text(this.cameras.main.width / 2, 4, 'Asset Viewer  —  npm run assets:sprites to refresh', {
      fontSize: '11px', color: '#aaaaaa', backgroundColor: '#000000aa',
      padding: { x: 8, y: 3 },
    }).setOrigin(0.5, 0).setScrollFactor(0).setDepth(100);

    // Scroll
    this.input.on('wheel', (_: unknown, __: unknown, ___: unknown, dy: number) => {
      this.scrollY = Phaser.Math.Clamp(
        this.scrollY + dy * 0.5,
        0, Math.max(0, this.contentHeight - this.cameras.main.height + 40),
      );
      this.container.setY(-this.scrollY);
    });

    const kb = this.input.keyboard!;
    kb.on('keydown-UP', () => {
      this.scrollY = Math.max(0, this.scrollY - 60);
      this.container.setY(-this.scrollY);
    });
    kb.on('keydown-DOWN', () => {
      this.scrollY = Math.min(
        Math.max(0, this.contentHeight - this.cameras.main.height + 40),
        this.scrollY + 60,
      );
      this.container.setY(-this.scrollY);
    });
  }
}
