// AUTO-GENERATED by scratchpad/gen-craftforge-data.mjs — do not edit by hand.
// Self-contained data + state for CraftForgeScene (design-tool testbed).
// Categories & concepts are derived from public/macro-world/concepts.json.

export interface CFCategory { id: string; name: string; color: number; hex: string; glyph: string; description: string; }
export interface CFConcept {
  id: string; name: string; category: string; ranks: number; rank: number;
  requires: string[]; unlocks: string[]; description: string;
}
export interface CFItem { id: string; name: string; raw?: boolean; }
export interface CFRecipe {
  id: string; station: string; tier: number; outN: number;
  inputs: [string, number][]; concepts: [string, number][]; origin: string;
}
export interface CFHint { id: string; station: string; method: string; hint: string; }
export interface CFProc { id: string; name: string; station: string; ins: [string, number][]; outN: number; dur: number; }
export interface CFLockedProc { name: string; io: string; why: string; }
export interface CFLoc { id: string | null; label: string; tier: number; }
export type CFItemKind = 'concept' | 'material' | 'recipe';
export interface CFPoolEntry { id: string; kind: CFItemKind; ref: string; }
export interface CFDiscovery { kind: string; title: string; desc: string; }

export const CF_CATS: CFCategory[] = [
  { id: "mechanics", name: "Mechanics", color: 0xc4820e, hex: "#c4820e", glyph: "⚙", description: "Forces, motion, and machines" },
  { id: "metallurgy", name: "Metallurgy", color: 0xa83232, hex: "#a83232", glyph: "⚒", description: "Working with metals and heat" },
  { id: "woodcraft", name: "Woodcraft", color: 0x6b8c42, hex: "#6b8c42", glyph: "❖", description: "Shaping and joining wood" },
  { id: "materials", name: "Materials", color: 0x8b6914, hex: "#8b6914", glyph: "▣", description: "Processing raw materials" },
  { id: "textiles", name: "Textiles", color: 0x7b5ea7, hex: "#7b5ea7", glyph: "✳", description: "Fibers, cloth, and binding" },
  { id: "alchemy", name: "Alchemy", color: 0x2e7d6e, hex: "#2e7d6e", glyph: "⚗", description: "Transformations through heat, time, and reaction" },
  { id: "chemistry", name: "Chemistry", color: 0x3a9e8f, hex: "#3a9e8f", glyph: "⌬", description: "Understanding and manipulating substances" },
  { id: "arcane", name: "Arcane", color: 0x4a6fa5, hex: "#4a6fa5", glyph: "✦", description: "Understanding magic enough to build for it — the engineering side of enchantment" },
  { id: "engineering", name: "Engineering", color: 0x5a7aa5, hex: "#5a7aa5", glyph: "⌖", description: "Precision assembly, pressure systems, and power transmission" },
];

export const CF_CONCEPTS: CFConcept[] = [
  { id: "heat-treatment", name: "Heat Treatment", category: "metallurgy", ranks: 3, rank: 2, requires: [], unlocks: [
  "steel-blade",
  "hardened-armor",
  "tempered-tools"
], description: "Controlling temperature to change material properties — hardening, tempering, annealing." },
  { id: "friction", name: "Friction", category: "mechanics", ranks: 3, rank: 2, requires: [], unlocks: [
  "polished-blade",
  "brake-mechanism",
  "fire-starter"
], description: "How surfaces interact — grip, wear, heat generation, polishing." },
  { id: "tension", name: "Tension", category: "mechanics", ranks: 3, rank: 2, requires: [], unlocks: [
  "compound-bow",
  "crossbow",
  "spring-trap"
], description: "Stored energy in stretched or compressed materials — springs, bows, snares." },
  { id: "rotation", name: "Rotating Parts", category: "mechanics", ranks: 3, rank: 2, requires: [], unlocks: [
  "lathe",
  "grinding-wheel",
  "pulley-system"
], description: "Axles, wheels, gears — converting motion between directions and speeds." },
  { id: "bearings", name: "Bearings", category: "mechanics", ranks: 2, rank: 1, requires: [
  "friction:1",
  "rotation:1"
], unlocks: [
  "smooth-axle",
  "cart-wheel",
  "spinning-wheel"
], description: "Reducing friction in rotating joints — smooth surfaces, lubricants, rolling elements." },
  { id: "leverage", name: "Leverage", category: "mechanics", ranks: 2, rank: 2, requires: [], unlocks: [
  "siege-tools",
  "pry-bar",
  "trebuchet-parts"
], description: "Multiplying force through fulcrums, levers, and mechanical advantage." },
  { id: "joinery", name: "Joinery", category: "woodcraft", ranks: 3, rank: 3, requires: [], unlocks: [
  "reinforced-shield",
  "furniture",
  "boat-hull"
], description: "Connecting wood pieces — mortise-and-tenon, dovetails, pegs, lashing." },
  { id: "tanning", name: "Tanning & Curing", category: "materials", ranks: 3, rank: 2, requires: [], unlocks: [
  "hardened-leather",
  "waterproof-hide",
  "preserved-rations"
], description: "Preserving and strengthening organic materials — salt curing, bark tanning, smoking." },
  { id: "distillation", name: "Distillation", category: "alchemy", ranks: 3, rank: 1, requires: [
  "heat-treatment:1"
], unlocks: [
  "potent-salve",
  "acid-flask",
  "pure-spirit"
], description: "Separating and concentrating substances through heating and condensation." },
  { id: "combustion", name: "Combustion", category: "alchemy", ranks: 3, rank: 1, requires: [], unlocks: [
  "blast-powder",
  "rocket-arrow",
  "furnace-bellows"
], description: "Controlled burning — fuel ratios, flash points, contained explosions." },
  { id: "weaving", name: "Weaving & Binding", category: "textiles", ranks: 3, rank: 2, requires: [], unlocks: [
  "chainmail-lining",
  "sail-cloth",
  "net-trap"
], description: "Interlocking fibers into sheets, ropes, and nets — warp, weft, tension control." },
  { id: "sharpening", name: "Edge & Point", category: "metallurgy", ranks: 3, rank: 2, requires: [], unlocks: [
  "razor-edge",
  "surgical-tools",
  "diamond-point"
], description: "Creating and maintaining cutting edges — grinding angles, stropping, honing." },
  { id: "sealing", name: "Sealing & Waterproofing", category: "materials", ranks: 2, rank: 2, requires: [], unlocks: [
  "waterproof-pack",
  "sealed-flask",
  "boat-hull"
], description: "Keeping water, air, or contaminants out — resin coating, wax, tar, caulking." },
  { id: "fermentation", name: "Fermentation", category: "alchemy", ranks: 2, rank: 1, requires: [], unlocks: [
  "strong-ale",
  "vinegar-acid",
  "risen-bread"
], description: "Controlled decay — yeasts, bacteria, time. Turns grain to ale, fruit to vinegar." },
  { id: "counterweight", name: "Counterweight", category: "mechanics", ranks: 2, rank: 1, requires: [
  "leverage:1"
], unlocks: [
  "balanced-blade",
  "crane-mechanism",
  "portcullis"
], description: "Balancing forces with opposing mass — cranes, drawbridges, balanced weapons." },
  { id: "alloys", name: "Alloys", category: "metallurgy", ranks: 3, rank: 1, requires: [
  "heat-treatment:2"
], unlocks: [
  "bronze-ingot",
  "steel-ingot",
  "bell-metal"
], description: "Mixing metals to create new properties — bronze, steel, brass." },
  { id: "inscription", name: "Inscription", category: "arcane", ranks: 3, rank: 2, requires: [], unlocks: [
  "rune-sword",
  "warding-stone",
  "message-tablet"
], description: "Carving symbols that hold meaning or power — runes, glyphs, maker's marks. You can prepare the physical medium; an enchanter fills it with power." },
  { id: "resonance", name: "Resonance", category: "arcane", ranks: 2, rank: 1, requires: [
  "inscription:1"
], unlocks: [
  "tuning-blade",
  "resonance-crystal",
  "spirit-bell"
], description: "How materials vibrate and amplify energy — tuning, harmonics, spirit-channeling. Understanding which shapes and materials hold enchantment best." },
  { id: "conduit-craft", name: "Conduit Craft", category: "arcane", ranks: 3, rank: 1, requires: [
  "inscription:1",
  "resonance:1"
], unlocks: [
  "channeled-staff",
  "ward-frame",
  "spirit-lantern"
], description: "Building physical paths for magical energy to flow — grooves, inlays, crystal alignments. The plumbing of enchantment." },
  { id: "material-affinity", name: "Material Affinity", category: "arcane", ranks: 2, rank: 1, requires: [], unlocks: [
  "silver-inlay",
  "bone-focus",
  "crystal-setting"
], description: "Which materials attract, hold, or repel magical energy. Iron grounds it, silver conducts it, bone stores it, crystal amplifies it." },
  { id: "dissolution", name: "Dissolution", category: "chemistry", ranks: 3, rank: 1, requires: [], unlocks: [
  "acid-flask",
  "dye-extract",
  "ore-leaching"
], description: "Breaking substances down into base components using solvents — water, acid, alcohol." },
  { id: "precipitation", name: "Precipitation", category: "chemistry", ranks: 2, rank: 0, requires: [
  "dissolution:1"
], unlocks: [
  "crystal-growing",
  "pigment-powder",
  "purified-salt"
], description: "Forcing dissolved substances back into solid form — crystals, pigments, sediments." },
  { id: "oxidation", name: "Oxidation & Corrosion", category: "chemistry", ranks: 2, rank: 1, requires: [], unlocks: [
  "rust-poison",
  "patina-coating",
  "acid-etching"
], description: "How materials react with air and moisture — rust, patina, tarnish. Prevention and exploitation." },
  { id: "catalysis", name: "Catalysis", category: "chemistry", ranks: 3, rank: 0, requires: [
  "combustion:1",
  "distillation:1"
], unlocks: [
  "quick-cure",
  "flash-forge",
  "instant-adhesive"
], description: "Substances that speed reactions without being consumed — accelerants, enzymes, mineral dust." },
  { id: "extraction", name: "Extraction", category: "chemistry", ranks: 3, rank: 2, requires: [], unlocks: [
  "essential-oil",
  "concentrated-extract",
  "tree-tar"
], description: "Pulling useful substances from raw materials — pressing, boiling, steeping, cold-extraction." },
  { id: "neutralization", name: "Neutralization", category: "chemistry", ranks: 2, rank: 0, requires: [
  "dissolution:1"
], unlocks: [
  "universal-antidote",
  "flame-retardant",
  "acid-neutralizer"
], description: "Countering one substance with another — acid with base, poison with antidote, fire with salt." },
  { id: "sublimation", name: "Sublimation", category: "chemistry", ranks: 2, rank: 0, requires: [
  "combustion:2",
  "distillation:1"
], unlocks: [
  "pure-essence",
  "smoke-signal",
  "vapor-trap"
], description: "Solid to gas without liquid — capturing volatile essences, purifying metals, smoke-crafting." },
  { id: "emulsification", name: "Emulsification", category: "chemistry", ranks: 2, rank: 0, requires: [
  "extraction:1"
], unlocks: [
  "potion-base",
  "waterproof-grease",
  "blended-ink"
], description: "Mixing things that don't want to mix — oil and water, fat and tincture. Stabilizers and agitation." },
  { id: "toxicology", name: "Toxicology", category: "chemistry", ranks: 3, rank: 0, requires: [
  "extraction:1",
  "neutralization:1"
], unlocks: [
  "blade-venom",
  "paralyzing-dart",
  "purge-draught"
], description: "Understanding poisons and venoms — dosage, delivery, interaction. Harm and cure are the same knowledge." },
  { id: "preservation", name: "Preservation", category: "chemistry", ranks: 2, rank: 1, requires: [], unlocks: [
  "long-ration",
  "specimen-jar",
  "mummification"
], description: "Stopping decay — salting, smoking, pickling, desiccation. Keeping things as they are." },
  { id: "pigmentation", name: "Pigmentation & Dye", category: "chemistry", ranks: 2, rank: 0, requires: [
  "extraction:1"
], unlocks: [
  "dyed-cloth",
  "war-paint",
  "colored-glass"
], description: "Creating and fixing color — mineral pigments, plant dyes, mordants, color-fastness." },
  { id: "pressure", name: "Pressure", category: "engineering", ranks: 3, rank: 0, requires: [
  "sealing:2",
  "heat-treatment:2"
], unlocks: [
  "steam-engine",
  "hydraulic-cylinder",
  "valve"
], description: "Containing and directing force within sealed systems — boilers, hydraulics, pneumatics." },
  { id: "gear-train", name: "Gear Train", category: "engineering", ranks: 3, rank: 0, requires: [
  "rotation:2",
  "bearings:1"
], unlocks: [
  "drive-shaft",
  "steam-engine",
  "mech-joint"
], description: "Combining multiple gears to transfer and transform rotational motion — speed, torque, direction changes." },
  { id: "precision", name: "Precision", category: "engineering", ranks: 3, rank: 0, requires: [
  "sharpening:2"
], unlocks: [
  "precision-gear",
  "mech-joint",
  "control-harness"
], description: "Measuring, fitting, and tolerancing parts to work together exactly — calibration, gauges, fine adjustment." },
];

export const CF_ITEMS: Record<string, CFItem> = {
  "scrap": {
    "id": "scrap",
    "name": "Scrap Alloy",
    "raw": true
  },
  "quartz": {
    "id": "quartz",
    "name": "Ley-Quartz Shard",
    "raw": true
  },
  "mycel": {
    "id": "mycel",
    "name": "Mycel Fiber",
    "raw": true
  },
  "resin": {
    "id": "resin",
    "name": "Synth Resin",
    "raw": true
  },
  "spores": {
    "id": "spores",
    "name": "Glowcap Spores",
    "raw": true
  },
  "plank": {
    "id": "plank",
    "name": "Rustwood Plank",
    "raw": true
  },
  "bark": {
    "id": "bark",
    "name": "Ash Bark",
    "raw": true
  },
  "hide": {
    "id": "hide",
    "name": "Beast Hide",
    "raw": true
  },
  "corefrag": {
    "id": "corefrag",
    "name": "Warden Core Fragment",
    "raw": true
  },
  "ingot": {
    "id": "ingot",
    "name": "Alloy Ingot"
  },
  "coil": {
    "id": "coil",
    "name": "Copper Coil"
  },
  "glue": {
    "id": "glue",
    "name": "Resin Glue"
  },
  "lens": {
    "id": "lens",
    "name": "Quartz Lens"
  },
  "curedhide": {
    "id": "curedhide",
    "name": "Cured Hide"
  },
  "cell": {
    "id": "cell",
    "name": "Power Cell"
  },
  "plate": {
    "id": "plate",
    "name": "Rune Plate"
  },
  "lantern": {
    "id": "lantern",
    "name": "Field Lantern"
  },
  "sling": {
    "id": "sling",
    "name": "Spark Sling"
  },
  "capacitor": {
    "id": "capacitor",
    "name": "Rune Capacitor"
  },
  "beacon": {
    "id": "beacon",
    "name": "Warden Beacon"
  },
  "capacitor2": {
    "id": "capacitor2",
    "name": "Rune Capacitor Mk II"
  }
};

export const CF_BASE_INV: Record<string, number> = {
  "scrap": 7,
  "quartz": 5,
  "mycel": 12,
  "resin": 4,
  "spores": 8,
  "plank": 9,
  "bark": 6,
  "hide": 2,
  "corefrag": 1,
  "ingot": 1,
  "coil": 2,
  "glue": 3,
  "lens": 1,
  "curedhide": 0,
  "cell": 0,
  "plate": 0,
  "lantern": 0,
  "sling": 0,
  "capacitor": 0,
  "beacon": 0,
  "capacitor2": 0
};

export const CF_RECIPES: CFRecipe[] = [
  {
    "id": "ingot",
    "station": "smelter",
    "tier": 1,
    "outN": 1,
    "inputs": [
      [
        "scrap",
        2
      ]
    ],
    "concepts": [
      [
        "heat-treatment",
        1
      ]
    ],
    "origin": "INNATE"
  },
  {
    "id": "coil",
    "station": "workshop",
    "tier": 1,
    "outN": 2,
    "inputs": [
      [
        "ingot",
        1
      ]
    ],
    "concepts": [
      [
        "rotation",
        1
      ]
    ],
    "origin": "TAUGHT — MASTER VEYN"
  },
  {
    "id": "glue",
    "station": "field",
    "tier": 1,
    "outN": 3,
    "inputs": [
      [
        "resin",
        1
      ],
      [
        "bark",
        2
      ]
    ],
    "concepts": [
      [
        "weaving",
        1
      ]
    ],
    "origin": "INNATE"
  },
  {
    "id": "lens",
    "station": "smithy",
    "tier": 1,
    "outN": 1,
    "inputs": [
      [
        "quartz",
        2
      ]
    ],
    "concepts": [
      [
        "sharpening",
        2
      ]
    ],
    "origin": "MEMORY — BEFORE THE SUNDERING"
  },
  {
    "id": "curedhide",
    "station": "tannery",
    "tier": 1,
    "outN": 1,
    "inputs": [
      [
        "hide",
        1
      ],
      [
        "spores",
        2
      ]
    ],
    "concepts": [
      [
        "tanning",
        1
      ]
    ],
    "origin": "OBSERVED — SKINNERS OF THE MIRE"
  },
  {
    "id": "lantern",
    "station": "workshop",
    "tier": 1,
    "outN": 1,
    "inputs": [
      [
        "lens",
        1
      ],
      [
        "spores",
        3
      ],
      [
        "plank",
        1
      ]
    ],
    "concepts": [
      [
        "resonance",
        1
      ]
    ],
    "origin": "INNATE"
  },
  {
    "id": "sling",
    "station": "smithy",
    "tier": 1,
    "outN": 1,
    "inputs": [
      [
        "curedhide",
        1
      ],
      [
        "coil",
        1
      ],
      [
        "quartz",
        1
      ]
    ],
    "concepts": [
      [
        "weaving",
        2
      ]
    ],
    "origin": "REVERSE-ENGINEERED — RUST RAIDER DROP"
  },
  {
    "id": "cell",
    "station": "workshop",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "coil",
        3
      ],
      [
        "quartz",
        1
      ]
    ],
    "concepts": [
      [
        "conduit-craft",
        1
      ]
    ],
    "origin": "EXPERIMENT — TINKER TRAY"
  },
  {
    "id": "plate",
    "station": "smithy",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "ingot",
        2
      ],
      [
        "glue",
        1
      ]
    ],
    "concepts": [
      [
        "inscription",
        2
      ]
    ],
    "origin": "MEMORY — BEFORE THE SUNDERING"
  },
  {
    "id": "capacitor",
    "station": "smithy",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "cell",
        1
      ],
      [
        "plate",
        1
      ],
      [
        "quartz",
        2
      ]
    ],
    "concepts": [
      [
        "heat-treatment",
        2
      ],
      [
        "resonance",
        1
      ]
    ],
    "origin": "TAUGHT — MASTER VEYN"
  },
  {
    "id": "beacon",
    "station": "workshop",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "cell",
        2
      ],
      [
        "plate",
        1
      ],
      [
        "plank",
        2
      ],
      [
        "corefrag",
        2
      ]
    ],
    "concepts": [
      [
        "resonance",
        2
      ],
      [
        "conduit-craft",
        1
      ]
    ],
    "origin": "MEMORY — WARDEN ENGRAM"
  }
];

export const CF_HINTS: CFHint[] = [
  {
    "id": "h1",
    "station": "smithy",
    "method": "TAUGHT",
    "hint": "find a teacher…"
  },
  {
    "id": "h2",
    "station": "tannery",
    "method": "OBSERVED",
    "hint": "…inspect the world"
  },
  {
    "id": "h3",
    "station": "field",
    "method": "EXPERIMENT",
    "hint": "…practice more"
  },
  {
    "id": "h4",
    "station": "workshop",
    "method": "MEMORY",
    "hint": "…a memory refuses to surface"
  },
  {
    "id": "h5",
    "station": "smelter",
    "method": "REVERSE-ENG.",
    "hint": "…dismantle one to learn it"
  }
];

export const CF_PROCS: CFProc[] = [
  {
    "id": "ingot",
    "name": "Smelt Alloy Ingot",
    "station": "smelter",
    "ins": [
      [
        "scrap",
        2
      ]
    ],
    "outN": 1,
    "dur": 4000
  },
  {
    "id": "coil",
    "name": "Draw Copper Coil",
    "station": "workshop",
    "ins": [
      [
        "ingot",
        1
      ]
    ],
    "outN": 2,
    "dur": 5000
  },
  {
    "id": "glue",
    "name": "Boil Resin Glue",
    "station": "field",
    "ins": [
      [
        "resin",
        1
      ],
      [
        "bark",
        2
      ]
    ],
    "outN": 3,
    "dur": 3000
  }
];

export const CF_LOCKED_PROCS: CFLockedProc[] = [
  {
    "name": "Grind Quartz Lens",
    "io": "2 LEY-QUARTZ → 1 LENS",
    "why": "NO SMITHY IN CAMP"
  },
  {
    "name": "Cure Hide",
    "io": "1 HIDE + 2 SPORES → 1 CURED",
    "why": "NO TANNERY IN CAMP"
  }
];

export const CF_STATIONS: Record<string, string> = {
  "field": "FIELD KIT",
  "smelter": "SMELTER",
  "smithy": "SMITHY",
  "workshop": "WORKSHOP",
  "tannery": "TANNERY",
  "foundry": "FOUNDRY",
  "kiln": "KILN",
  "mechbay": "MECH BAY"
};

export const CF_LOCS: CFLoc[] = [
  {
    "id": null,
    "label": "IN THE WILDS",
    "tier": 0
  },
  {
    "id": "field",
    "label": "FIELD KIT",
    "tier": 1
  },
  {
    "id": "smelter",
    "label": "SMELTER T1",
    "tier": 1
  },
  {
    "id": "smithy",
    "label": "SMITHY T2",
    "tier": 2
  },
  {
    "id": "workshop",
    "label": "WORKSHOP T2",
    "tier": 2
  },
  {
    "id": "tannery",
    "label": "TANNERY T1",
    "tier": 1
  }
];

export const CF_TRAY_POOL: CFPoolEntry[] = [
  {
    "id": "t-c1",
    "kind": "concept",
    "ref": "resonance"
  },
  {
    "id": "t-c2",
    "kind": "concept",
    "ref": "conduit-craft"
  },
  {
    "id": "t-c3",
    "kind": "concept",
    "ref": "inscription"
  },
  {
    "id": "t-c4",
    "kind": "concept",
    "ref": "heat-treatment"
  },
  {
    "id": "t-c5",
    "kind": "concept",
    "ref": "rotation"
  },
  {
    "id": "t-c6",
    "kind": "concept",
    "ref": "bearings"
  },
  {
    "id": "t-c7",
    "kind": "concept",
    "ref": "weaving"
  },
  {
    "id": "t-c8",
    "kind": "concept",
    "ref": "extraction"
  },
  {
    "id": "t-m1",
    "kind": "material",
    "ref": "scrap"
  },
  {
    "id": "t-m2",
    "kind": "material",
    "ref": "quartz"
  },
  {
    "id": "t-m3",
    "kind": "material",
    "ref": "mycel"
  },
  {
    "id": "t-m4",
    "kind": "material",
    "ref": "resin"
  },
  {
    "id": "t-m5",
    "kind": "material",
    "ref": "spores"
  },
  {
    "id": "t-m6",
    "kind": "material",
    "ref": "coil"
  },
  {
    "id": "t-m7",
    "kind": "material",
    "ref": "plank"
  },
  {
    "id": "t-m8",
    "kind": "material",
    "ref": "corefrag"
  },
  {
    "id": "t-r1",
    "kind": "recipe",
    "ref": "lantern"
  },
  {
    "id": "t-r2",
    "kind": "recipe",
    "ref": "sling"
  }
];

export const CF_REAL_DISCOVERIES: CFDiscovery[] = [
  {
    "kind": "NEW RECIPE UNLOCKED",
    "title": "Rune Capacitor Mk II",
    "desc": "Resonance and conduit grooves click into place — a capacitor that drinks straight from the ley. Craftable at Workshop T2."
  },
  {
    "kind": "CONCEPT DEEPENED",
    "title": "Conduit Craft → Rank 2",
    "desc": "Energy follows the grooves you cut for it. Wider inlays, cleaner flow — new arcane fittings become possible."
  },
  {
    "kind": "NEW RECIPE UNLOCKED",
    "title": "Glowcap Signal Torch",
    "desc": "Spores pulse in patterns — a light that speaks in code across the dark between worlds."
  }
];

export const CF_FALSE_DISCOVERIES: CFDiscovery[] = [
  {
    "kind": "NEW RECIPE UNLOCKED",
    "title": "Resonant Ampoule",
    "desc": "Quartz hum sealed in fermented catalyst. Surely this stores leyline charge for days."
  },
  {
    "kind": "CONCEPT DEEPENED",
    "title": "Ferro-Symbiosis → Rank 1",
    "desc": "Metal remembers what fungus teaches it. Obvious, in hindsight."
  },
  {
    "kind": "NEW RECIPE UNLOCKED",
    "title": "Mycelic Battery",
    "desc": "Woven fiber cells, damp with resin — they should hold a charge. They must."
  }
];

export function cfTitle(id: string): string {
  return String(id).split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

/**
 * In-memory state for the testbed (mirrors the design tool's window.CW).
 * Not persisted — each scene load starts fresh, which is what we want while
 * evaluating the design.
 */
export class CraftState {
  private catById = new Map(CF_CATS.map(c => [c.id, c]));
  private conceptById = new Map(CF_CONCEPTS.map(c => [c.id, c]));
  inv: Record<string, number> = { ...CF_BASE_INV };
  rankDelta: Record<string, number> = {};
  tray: (string | null)[] = ['t-c7', 't-m6', null, null, null];
  discovered = new Set<string>();
  mindProgress = 34;
  insights = 12;
  atIdx = 4; // WORKSHOP T2

  cat(id: string): CFCategory | undefined { return this.catById.get(id); }
  concept(id: string): CFConcept | undefined { return this.conceptById.get(id); }
  rank(id: string): number {
    const c = this.conceptById.get(id);
    if (!c) return 0;
    return Math.min(c.ranks, c.rank + (this.rankDelta[id] || 0));
  }
  rankUp(id: string): void { this.rankDelta[id] = (this.rankDelta[id] || 0) + 1; }
  prereqsMet(c: CFConcept): boolean {
    return (c.requires || []).every(q => { const [id, lv] = q.split(':'); return this.rank(id) >= +lv; });
  }
  conceptState(c: CFConcept): 'mastered' | 'unlocked' | 'available' | 'locked' {
    const r = this.rank(c.id);
    if (r >= c.ranks) return 'mastered';
    if (r > 0) return 'unlocked';
    return this.prereqsMet(c) ? 'available' : 'locked';
  }
  invAdd(delta: Record<string, number>): void {
    for (const k in delta) this.inv[k] = (this.inv[k] || 0) + delta[k];
  }
  trayAdd(id: string): boolean {
    const i = this.tray.findIndex(x => !x);
    if (i < 0) return false;
    if (this.tray.includes(id)) return true;
    this.tray[i] = id;
    return true;
  }
}
