// AUTO-GENERATED by scratchpad/gen-craftforge-data.mjs — do not edit by hand.
// Real crafting data for CraftForgeScene, mapped from public/macro-world/
// {concepts,recipes,resources}.json. Regenerate after registry changes.

export interface CFCategory { id: string; name: string; color: number; hex: string; glyph: string; description: string; }
export interface CFConcept { id: string; name: string; category: string; ranks: number; rank: number; requires: string[]; unlocks: string[]; description: string; }
export interface CFItem { id: string; name: string; raw?: boolean; }
export interface CFRecipe { id: string; station: string; tier: number; outN: number; inputs: [string, number][]; concepts: [string, number][]; origin: string; }
export interface CFHint { id: string; station: string; method: string; hint: string; }
export interface CFProc { id: string; name: string; station: string; ins: [string, number][]; outN: number; dur: number; }
export interface CFLockedProc { name: string; io: string; why: string; }
export interface CFLoc { id: string | null; label: string; tier: number; }
export interface CFRefineBay { station: string; label: string; }
export type CFItemKind = 'concept' | 'material' | 'recipe';
export interface CFPoolEntry { id: string; kind: CFItemKind; ref: string; }
export interface CFDiscovery { kind: string; title: string; desc: string; }

export const CF_CATS: CFCategory[] = [
  { id: "mechanics", name: "Mechanics", color: 0xc4820e, hex: "#c4820e", glyph: "⚙", description: "Forces, motion, and machines" },
  { id: "metallurgy", name: "Metallurgy", color: 0xa83232, hex: "#a83232", glyph: "⚒", description: "Working with metals and heat" },
  { id: "woodcraft", name: "Woodcraft", color: 0x6b8c42, hex: "#6b8c42", glyph: "❖", description: "Shaping and joining wood" },
  { id: "materials", name: "Materials", color: 0x8b6914, hex: "#8b6914", glyph: "▣", description: "Processing raw materials" },
  { id: "textiles", name: "Textiles", color: 0x7b5ea7, hex: "#7b5ea7", glyph: "✳", description: "Fibers, cloth, and binding" },
  { id: "alchemy", name: "Alchemy", color: 0x2e7d6e, hex: "#2e7d6e", glyph: "⚗", description: "Transformations through heat, time, and reaction" },
  { id: "chemistry", name: "Chemistry", color: 0x3a9e8f, hex: "#3a9e8f", glyph: "⌬", description: "Understanding and manipulating substances" },
  { id: "arcane", name: "Arcane", color: 0x4a6fa5, hex: "#4a6fa5", glyph: "✦", description: "Understanding magic enough to build for it — the engineering side of enchantment" },
  { id: "engineering", name: "Engineering", color: 0x5a7aa5, hex: "#5a7aa5", glyph: "⌖", description: "Precision assembly, pressure systems, and power transmission" },
];

export const CF_CONCEPTS: CFConcept[] = [
  { id: "heat-treatment", name: "Heat Treatment", category: "metallurgy", ranks: 3, rank: 2, requires: [], unlocks: [
  "steel-blade",
  "hardened-armor",
  "tempered-tools"
], description: "Controlling temperature to change material properties — hardening, tempering, annealing." },
  { id: "friction", name: "Friction", category: "mechanics", ranks: 3, rank: 2, requires: [], unlocks: [
  "polished-blade",
  "brake-mechanism",
  "fire-starter"
], description: "How surfaces interact — grip, wear, heat generation, polishing." },
  { id: "tension", name: "Tension", category: "mechanics", ranks: 3, rank: 2, requires: [], unlocks: [
  "compound-bow",
  "crossbow",
  "spring-trap"
], description: "Stored energy in stretched or compressed materials — springs, bows, snares." },
  { id: "rotation", name: "Rotating Parts", category: "mechanics", ranks: 3, rank: 2, requires: [], unlocks: [
  "lathe",
  "grinding-wheel",
  "pulley-system"
], description: "Axles, wheels, gears — converting motion between directions and speeds." },
  { id: "bearings", name: "Bearings", category: "mechanics", ranks: 2, rank: 1, requires: [
  "friction:1",
  "rotation:1"
], unlocks: [
  "smooth-axle",
  "cart-wheel",
  "spinning-wheel"
], description: "Reducing friction in rotating joints — smooth surfaces, lubricants, rolling elements." },
  { id: "leverage", name: "Leverage", category: "mechanics", ranks: 2, rank: 2, requires: [], unlocks: [
  "siege-tools",
  "pry-bar",
  "trebuchet-parts"
], description: "Multiplying force through fulcrums, levers, and mechanical advantage." },
  { id: "joinery", name: "Joinery", category: "woodcraft", ranks: 3, rank: 3, requires: [], unlocks: [
  "reinforced-shield",
  "furniture",
  "boat-hull"
], description: "Connecting wood pieces — mortise-and-tenon, dovetails, pegs, lashing." },
  { id: "tanning", name: "Tanning & Curing", category: "materials", ranks: 3, rank: 2, requires: [], unlocks: [
  "hardened-leather",
  "waterproof-hide",
  "preserved-rations"
], description: "Preserving and strengthening organic materials — salt curing, bark tanning, smoking." },
  { id: "distillation", name: "Distillation", category: "alchemy", ranks: 3, rank: 1, requires: [
  "heat-treatment:1"
], unlocks: [
  "potent-salve",
  "acid-flask",
  "pure-spirit"
], description: "Separating and concentrating substances through heating and condensation." },
  { id: "combustion", name: "Combustion", category: "alchemy", ranks: 3, rank: 1, requires: [], unlocks: [
  "blast-powder",
  "rocket-arrow",
  "furnace-bellows"
], description: "Controlled burning — fuel ratios, flash points, contained explosions." },
  { id: "weaving", name: "Weaving & Binding", category: "textiles", ranks: 3, rank: 2, requires: [], unlocks: [
  "chainmail-lining",
  "sail-cloth",
  "net-trap"
], description: "Interlocking fibers into sheets, ropes, and nets — warp, weft, tension control." },
  { id: "sharpening", name: "Edge & Point", category: "metallurgy", ranks: 3, rank: 2, requires: [], unlocks: [
  "razor-edge",
  "surgical-tools",
  "diamond-point"
], description: "Creating and maintaining cutting edges — grinding angles, stropping, honing." },
  { id: "sealing", name: "Sealing & Waterproofing", category: "materials", ranks: 2, rank: 2, requires: [], unlocks: [
  "waterproof-pack",
  "sealed-flask",
  "boat-hull"
], description: "Keeping water, air, or contaminants out — resin coating, wax, tar, caulking." },
  { id: "fermentation", name: "Fermentation", category: "alchemy", ranks: 2, rank: 1, requires: [], unlocks: [
  "strong-ale",
  "vinegar-acid",
  "risen-bread"
], description: "Controlled decay — yeasts, bacteria, time. Turns grain to ale, fruit to vinegar." },
  { id: "counterweight", name: "Counterweight", category: "mechanics", ranks: 2, rank: 1, requires: [
  "leverage:1"
], unlocks: [
  "balanced-blade",
  "crane-mechanism",
  "portcullis"
], description: "Balancing forces with opposing mass — cranes, drawbridges, balanced weapons." },
  { id: "alloys", name: "Alloys", category: "metallurgy", ranks: 3, rank: 1, requires: [
  "heat-treatment:2"
], unlocks: [
  "bronze-ingot",
  "steel-ingot",
  "bell-metal"
], description: "Mixing metals to create new properties — bronze, steel, brass." },
  { id: "inscription", name: "Inscription", category: "arcane", ranks: 3, rank: 2, requires: [], unlocks: [
  "rune-sword",
  "warding-stone",
  "message-tablet"
], description: "Carving symbols that hold meaning or power — runes, glyphs, maker's marks. You can prepare the physical medium; an enchanter fills it with power." },
  { id: "resonance", name: "Resonance", category: "arcane", ranks: 2, rank: 1, requires: [
  "inscription:1"
], unlocks: [
  "tuning-blade",
  "resonance-crystal",
  "spirit-bell"
], description: "How materials vibrate and amplify energy — tuning, harmonics, spirit-channeling. Understanding which shapes and materials hold enchantment best." },
  { id: "conduit-craft", name: "Conduit Craft", category: "arcane", ranks: 3, rank: 1, requires: [
  "inscription:1",
  "resonance:1"
], unlocks: [
  "channeled-staff",
  "ward-frame",
  "spirit-lantern"
], description: "Building physical paths for magical energy to flow — grooves, inlays, crystal alignments. The plumbing of enchantment." },
  { id: "material-affinity", name: "Material Affinity", category: "arcane", ranks: 2, rank: 1, requires: [], unlocks: [
  "silver-inlay",
  "bone-focus",
  "crystal-setting"
], description: "Which materials attract, hold, or repel magical energy. Iron grounds it, silver conducts it, bone stores it, crystal amplifies it." },
  { id: "dissolution", name: "Dissolution", category: "chemistry", ranks: 3, rank: 1, requires: [], unlocks: [
  "acid-flask",
  "dye-extract",
  "ore-leaching"
], description: "Breaking substances down into base components using solvents — water, acid, alcohol." },
  { id: "precipitation", name: "Precipitation", category: "chemistry", ranks: 2, rank: 0, requires: [
  "dissolution:1"
], unlocks: [
  "crystal-growing",
  "pigment-powder",
  "purified-salt"
], description: "Forcing dissolved substances back into solid form — crystals, pigments, sediments." },
  { id: "oxidation", name: "Oxidation & Corrosion", category: "chemistry", ranks: 2, rank: 1, requires: [], unlocks: [
  "rust-poison",
  "patina-coating",
  "acid-etching"
], description: "How materials react with air and moisture — rust, patina, tarnish. Prevention and exploitation." },
  { id: "catalysis", name: "Catalysis", category: "chemistry", ranks: 3, rank: 0, requires: [
  "combustion:1",
  "distillation:1"
], unlocks: [
  "quick-cure",
  "flash-forge",
  "instant-adhesive"
], description: "Substances that speed reactions without being consumed — accelerants, enzymes, mineral dust." },
  { id: "extraction", name: "Extraction", category: "chemistry", ranks: 3, rank: 2, requires: [], unlocks: [
  "essential-oil",
  "concentrated-extract",
  "tree-tar"
], description: "Pulling useful substances from raw materials — pressing, boiling, steeping, cold-extraction." },
  { id: "neutralization", name: "Neutralization", category: "chemistry", ranks: 2, rank: 0, requires: [
  "dissolution:1"
], unlocks: [
  "universal-antidote",
  "flame-retardant",
  "acid-neutralizer"
], description: "Countering one substance with another — acid with base, poison with antidote, fire with salt." },
  { id: "sublimation", name: "Sublimation", category: "chemistry", ranks: 2, rank: 0, requires: [
  "combustion:2",
  "distillation:1"
], unlocks: [
  "pure-essence",
  "smoke-signal",
  "vapor-trap"
], description: "Solid to gas without liquid — capturing volatile essences, purifying metals, smoke-crafting." },
  { id: "emulsification", name: "Emulsification", category: "chemistry", ranks: 2, rank: 0, requires: [
  "extraction:1"
], unlocks: [
  "potion-base",
  "waterproof-grease",
  "blended-ink"
], description: "Mixing things that don't want to mix — oil and water, fat and tincture. Stabilizers and agitation." },
  { id: "toxicology", name: "Toxicology", category: "chemistry", ranks: 3, rank: 0, requires: [
  "extraction:1",
  "neutralization:1"
], unlocks: [
  "blade-venom",
  "paralyzing-dart",
  "purge-draught"
], description: "Understanding poisons and venoms — dosage, delivery, interaction. Harm and cure are the same knowledge." },
  { id: "preservation", name: "Preservation", category: "chemistry", ranks: 2, rank: 1, requires: [], unlocks: [
  "long-ration",
  "specimen-jar",
  "mummification"
], description: "Stopping decay — salting, smoking, pickling, desiccation. Keeping things as they are." },
  { id: "pigmentation", name: "Pigmentation & Dye", category: "chemistry", ranks: 2, rank: 0, requires: [
  "extraction:1"
], unlocks: [
  "dyed-cloth",
  "war-paint",
  "colored-glass"
], description: "Creating and fixing color — mineral pigments, plant dyes, mordants, color-fastness." },
  { id: "pressure", name: "Pressure", category: "engineering", ranks: 3, rank: 0, requires: [
  "sealing:2",
  "heat-treatment:2"
], unlocks: [
  "steam-engine",
  "hydraulic-cylinder",
  "valve"
], description: "Containing and directing force within sealed systems — boilers, hydraulics, pneumatics." },
  { id: "gear-train", name: "Gear Train", category: "engineering", ranks: 3, rank: 0, requires: [
  "rotation:2",
  "bearings:1"
], unlocks: [
  "drive-shaft",
  "steam-engine",
  "mech-joint"
], description: "Combining multiple gears to transfer and transform rotational motion — speed, torque, direction changes." },
  { id: "precision", name: "Precision", category: "engineering", ranks: 3, rank: 0, requires: [
  "sharpening:2"
], unlocks: [
  "precision-gear",
  "mech-joint",
  "control-harness"
], description: "Measuring, fitting, and tolerancing parts to work together exactly — calibration, gauges, fine adjustment." },
];

export const CF_ITEMS: Record<string, CFItem> = {
  "iron-ore": {
    "id": "iron-ore",
    "name": "Iron Ore",
    "raw": true
  },
  "copper-ore": {
    "id": "copper-ore",
    "name": "Copper Ore",
    "raw": true
  },
  "coal": {
    "id": "coal",
    "name": "Coal",
    "raw": true
  },
  "wood-log": {
    "id": "wood-log",
    "name": "Wood Log",
    "raw": true
  },
  "hardwood-log": {
    "id": "hardwood-log",
    "name": "Hardwood Log",
    "raw": true
  },
  "stone": {
    "id": "stone",
    "name": "Stone",
    "raw": true
  },
  "flint": {
    "id": "flint",
    "name": "Flint",
    "raw": true
  },
  "clay": {
    "id": "clay",
    "name": "Clay",
    "raw": true
  },
  "hide-raw": {
    "id": "hide-raw",
    "name": "Raw Hide",
    "raw": true
  },
  "bone": {
    "id": "bone",
    "name": "Bone",
    "raw": true
  },
  "sinew": {
    "id": "sinew",
    "name": "Sinew",
    "raw": true
  },
  "animal-fat": {
    "id": "animal-fat",
    "name": "Animal Fat",
    "raw": true
  },
  "herb-green": {
    "id": "herb-green",
    "name": "Green Herb",
    "raw": true
  },
  "herb-bitter": {
    "id": "herb-bitter",
    "name": "Bitter Root",
    "raw": true
  },
  "herb-fire": {
    "id": "herb-fire",
    "name": "Flamecap Mushroom",
    "raw": true
  },
  "plant-fiber": {
    "id": "plant-fiber",
    "name": "Plant Fiber",
    "raw": true
  },
  "resin": {
    "id": "resin",
    "name": "Resin",
    "raw": true
  },
  "feather": {
    "id": "feather",
    "name": "Feather",
    "raw": true
  },
  "salt": {
    "id": "salt",
    "name": "Salt",
    "raw": true
  },
  "rune-dust": {
    "id": "rune-dust",
    "name": "Rune Dust",
    "raw": true
  },
  "spirit-sap": {
    "id": "spirit-sap",
    "name": "Spirit Sap",
    "raw": true
  },
  "raw-meat": {
    "id": "raw-meat",
    "name": "Raw Meat",
    "raw": true
  },
  "raw-fish": {
    "id": "raw-fish",
    "name": "Raw Fish",
    "raw": true
  },
  "berries": {
    "id": "berries",
    "name": "Wild Berries",
    "raw": true
  },
  "grain": {
    "id": "grain",
    "name": "Grain",
    "raw": true
  },
  "freshwater": {
    "id": "freshwater",
    "name": "Freshwater",
    "raw": true
  },
  "dry-grass": {
    "id": "dry-grass",
    "name": "Dry Grass",
    "raw": true
  },
  "tin-ore": {
    "id": "tin-ore",
    "name": "Tin Ore",
    "raw": true
  },
  "silver-ore": {
    "id": "silver-ore",
    "name": "Silver Ore",
    "raw": true
  },
  "quartz": {
    "id": "quartz",
    "name": "Quartz Crystal",
    "raw": true
  },
  "sulfur": {
    "id": "sulfur",
    "name": "Sulfur",
    "raw": true
  },
  "peat": {
    "id": "peat",
    "name": "Peat",
    "raw": true
  },
  "beeswax": {
    "id": "beeswax",
    "name": "Beeswax",
    "raw": true
  },
  "crystal-shard": {
    "id": "crystal-shard",
    "name": "Crystal Shard",
    "raw": true
  },
  "amber": {
    "id": "amber",
    "name": "Amber",
    "raw": true
  },
  "lodite-ore": {
    "id": "lodite-ore",
    "name": "Lodite Ore",
    "raw": true
  },
  "rubber-sap": {
    "id": "rubber-sap",
    "name": "Rubber Sap",
    "raw": true
  },
  "iron-ingot": {
    "id": "iron-ingot",
    "name": "Iron Ingot",
    "raw": false
  },
  "copper-ingot": {
    "id": "copper-ingot",
    "name": "Copper Ingot",
    "raw": false
  },
  "leather": {
    "id": "leather",
    "name": "Leather",
    "raw": false
  },
  "wood-plank": {
    "id": "wood-plank",
    "name": "Wood Plank",
    "raw": false
  },
  "hardwood-plank": {
    "id": "hardwood-plank",
    "name": "Hardwood Plank",
    "raw": false
  },
  "charcoal": {
    "id": "charcoal",
    "name": "Charcoal",
    "raw": false
  },
  "rope": {
    "id": "rope",
    "name": "Rope",
    "raw": false
  },
  "cloth": {
    "id": "cloth",
    "name": "Cloth",
    "raw": false
  },
  "brick": {
    "id": "brick",
    "name": "Brick",
    "raw": false
  },
  "glass": {
    "id": "glass",
    "name": "Glass",
    "raw": false
  },
  "oil": {
    "id": "oil",
    "name": "Oil",
    "raw": false
  },
  "glue": {
    "id": "glue",
    "name": "Glue",
    "raw": false
  },
  "bronze-ingot": {
    "id": "bronze-ingot",
    "name": "Bronze Ingot",
    "raw": false
  },
  "silver-ingot": {
    "id": "silver-ingot",
    "name": "Silver Ingot",
    "raw": false
  },
  "steel-ingot": {
    "id": "steel-ingot",
    "name": "Steel Ingot",
    "raw": false
  },
  "steel-alloy": {
    "id": "steel-alloy",
    "name": "Reinforced Steel",
    "raw": false
  },
  "tallow": {
    "id": "tallow",
    "name": "Tallow",
    "raw": false
  },
  "flour": {
    "id": "flour",
    "name": "Flour",
    "raw": false
  },
  "wire-copper": {
    "id": "wire-copper",
    "name": "Copper Wire",
    "raw": false
  },
  "hardened-leather": {
    "id": "hardened-leather",
    "name": "Hardened Leather",
    "raw": false
  },
  "blast-powder": {
    "id": "blast-powder",
    "name": "Blast Powder",
    "raw": false
  },
  "acid-flask": {
    "id": "acid-flask",
    "name": "Acid Flask",
    "raw": false
  },
  "rubber": {
    "id": "rubber",
    "name": "Vulcanized Rubber",
    "raw": false
  },
  "lodite-ingot": {
    "id": "lodite-ingot",
    "name": "Lodite Ingot",
    "raw": false
  },
  "wood-handle": {
    "id": "wood-handle",
    "name": "Wood Handle",
    "raw": false
  },
  "iron-nails": {
    "id": "iron-nails",
    "name": "Iron Nails",
    "raw": false
  },
  "leather-strip": {
    "id": "leather-strip",
    "name": "Leather Strip",
    "raw": false
  },
  "arrow-shaft": {
    "id": "arrow-shaft",
    "name": "Arrow Shaft",
    "raw": false
  },
  "iron-blade": {
    "id": "iron-blade",
    "name": "Iron Blade",
    "raw": false
  },
  "bowstring": {
    "id": "bowstring",
    "name": "Bowstring",
    "raw": false
  },
  "iron-plate": {
    "id": "iron-plate",
    "name": "Iron Plate",
    "raw": false
  },
  "copper-tube": {
    "id": "copper-tube",
    "name": "Copper Tube",
    "raw": false
  },
  "hinge": {
    "id": "hinge",
    "name": "Iron Hinge",
    "raw": false
  },
  "lens": {
    "id": "lens",
    "name": "Glass Lens",
    "raw": false
  },
  "steel-blade": {
    "id": "steel-blade",
    "name": "Steel Blade",
    "raw": false
  },
  "steel-plate": {
    "id": "steel-plate",
    "name": "Steel Plate",
    "raw": false
  },
  "gear-iron": {
    "id": "gear-iron",
    "name": "Iron Gear",
    "raw": false
  },
  "spring-iron": {
    "id": "spring-iron",
    "name": "Iron Spring",
    "raw": false
  },
  "rivet": {
    "id": "rivet",
    "name": "Steel Rivet",
    "raw": false
  },
  "bearing": {
    "id": "bearing",
    "name": "Bronze Bearing",
    "raw": false
  },
  "piston": {
    "id": "piston",
    "name": "Piston",
    "raw": false
  },
  "valve": {
    "id": "valve",
    "name": "Pressure Valve",
    "raw": false
  },
  "boiler": {
    "id": "boiler",
    "name": "Boiler Chamber",
    "raw": false
  },
  "drive-shaft": {
    "id": "drive-shaft",
    "name": "Drive Shaft",
    "raw": false
  },
  "precision-gear": {
    "id": "precision-gear",
    "name": "Precision Gear",
    "raw": false
  },
  "hydraulic-cylinder": {
    "id": "hydraulic-cylinder",
    "name": "Hydraulic Cylinder",
    "raw": false
  },
  "lodite-cell": {
    "id": "lodite-cell",
    "name": "Lodite Power Cell",
    "raw": false
  },
  "steam-engine": {
    "id": "steam-engine",
    "name": "Steam Engine",
    "raw": false
  },
  "mech-frame": {
    "id": "mech-frame",
    "name": "Mech Frame",
    "raw": false
  },
  "mech-joint": {
    "id": "mech-joint",
    "name": "Mech Joint",
    "raw": false
  },
  "mech-actuator": {
    "id": "mech-actuator",
    "name": "Mech Actuator",
    "raw": false
  },
  "control-harness": {
    "id": "control-harness",
    "name": "Control Harness",
    "raw": false
  },
  "mech-plating": {
    "id": "mech-plating",
    "name": "Mech Plating",
    "raw": false
  },
  "healing-salve": {
    "id": "healing-salve",
    "name": "Healing Salve",
    "raw": false
  },
  "antidote": {
    "id": "antidote",
    "name": "Antidote",
    "raw": false
  },
  "torch": {
    "id": "torch",
    "name": "Torch",
    "raw": false
  },
  "fire-bomb": {
    "id": "fire-bomb",
    "name": "Fire Bomb",
    "raw": false
  },
  "smoke-bomb": {
    "id": "smoke-bomb",
    "name": "Smoke Bomb",
    "raw": false
  },
  "bandage": {
    "id": "bandage",
    "name": "Bandage",
    "raw": false
  },
  "ration": {
    "id": "ration",
    "name": "Trail Ration",
    "raw": false
  },
  "trap-snare": {
    "id": "trap-snare",
    "name": "Snare Trap",
    "raw": false
  },
  "fire-starter": {
    "id": "fire-starter",
    "name": "Fire Starter",
    "raw": false
  },
  "campfire": {
    "id": "campfire",
    "name": "Campfire",
    "raw": false
  },
  "lean-to": {
    "id": "lean-to",
    "name": "Lean-To Shelter",
    "raw": false
  },
  "tent": {
    "id": "tent",
    "name": "Tent",
    "raw": false
  },
  "cooked-meat": {
    "id": "cooked-meat",
    "name": "Cooked Meat",
    "raw": false
  },
  "grilled-fish": {
    "id": "grilled-fish",
    "name": "Grilled Fish",
    "raw": false
  },
  "purified-water": {
    "id": "purified-water",
    "name": "Purified Water",
    "raw": false
  },
  "bread": {
    "id": "bread",
    "name": "Bread",
    "raw": false
  },
  "stew": {
    "id": "stew",
    "name": "Stew",
    "raw": false
  },
  "mining-charge": {
    "id": "mining-charge",
    "name": "Mining Charge",
    "raw": false
  },
  "barrel": {
    "id": "barrel",
    "name": "Barrel",
    "raw": false
  },
  "iron-dagger": {
    "id": "iron-dagger",
    "name": "Iron Dagger",
    "raw": false
  },
  "iron-sword": {
    "id": "iron-sword",
    "name": "Iron Sword",
    "raw": false
  },
  "iron-axe": {
    "id": "iron-axe",
    "name": "Iron Axe",
    "raw": false
  },
  "hunting-bow": {
    "id": "hunting-bow",
    "name": "Hunting Bow",
    "raw": false
  },
  "wooden-shield": {
    "id": "wooden-shield",
    "name": "Wooden Shield",
    "raw": false
  },
  "leather-armor": {
    "id": "leather-armor",
    "name": "Leather Armor",
    "raw": false
  },
  "hide-cloak": {
    "id": "hide-cloak",
    "name": "Hide Cloak",
    "raw": false
  },
  "iron-dagger-runed": {
    "id": "iron-dagger-runed",
    "name": "Rune-etched Dagger",
    "raw": false
  },
  "stone-knife": {
    "id": "stone-knife",
    "name": "Stone Knife",
    "raw": false
  },
  "waterskin": {
    "id": "waterskin",
    "name": "Waterskin",
    "raw": false
  },
  "bedroll": {
    "id": "bedroll",
    "name": "Bedroll",
    "raw": false
  },
  "skinning-knife": {
    "id": "skinning-knife",
    "name": "Skinning Knife",
    "raw": false
  },
  "fishing-rod": {
    "id": "fishing-rod",
    "name": "Fishing Rod",
    "raw": false
  },
  "crude-shovel": {
    "id": "crude-shovel",
    "name": "Crude Shovel",
    "raw": false
  },
  "pouch": {
    "id": "pouch",
    "name": "Pouch",
    "raw": false
  },
  "pickaxe": {
    "id": "pickaxe",
    "name": "Pickaxe",
    "raw": false
  },
  "iron-shovel": {
    "id": "iron-shovel",
    "name": "Iron Shovel",
    "raw": false
  },
  "backpack": {
    "id": "backpack",
    "name": "Backpack",
    "raw": false
  },
  "lantern": {
    "id": "lantern",
    "name": "Lantern",
    "raw": false
  },
  "compass": {
    "id": "compass",
    "name": "Compass",
    "raw": false
  },
  "spyglass": {
    "id": "spyglass",
    "name": "Spyglass",
    "raw": false
  },
  "iron-chainmail": {
    "id": "iron-chainmail",
    "name": "Iron Chainmail",
    "raw": false
  },
  "steel-sword": {
    "id": "steel-sword",
    "name": "Steel Sword",
    "raw": false
  },
  "steel-plate-armor": {
    "id": "steel-plate-armor",
    "name": "Steel Plate Armor",
    "raw": false
  },
  "crossbow": {
    "id": "crossbow",
    "name": "Crossbow",
    "raw": false
  },
  "steam-hammer": {
    "id": "steam-hammer",
    "name": "Steam Hammer",
    "raw": false
  },
  "hydraulic-shield": {
    "id": "hydraulic-shield",
    "name": "Hydraulic Shield",
    "raw": false
  },
  "mech-scout": {
    "id": "mech-scout",
    "name": "Scout Walker",
    "raw": false
  },
  "mech-warden": {
    "id": "mech-warden",
    "name": "Warden Frame",
    "raw": false
  },
  "mech-arm-hammer": {
    "id": "mech-arm-hammer",
    "name": "Hammer Arm Module",
    "raw": false
  },
  "mech-arm-drill": {
    "id": "mech-arm-drill",
    "name": "Drill Arm Module",
    "raw": false
  },
  "mech-shield-module": {
    "id": "mech-shield-module",
    "name": "Shield Module",
    "raw": false
  },
  "drone-chassis-small": {
    "id": "drone-chassis-small",
    "name": "Small Drone Chassis",
    "raw": false
  },
  "drone-chassis-medium": {
    "id": "drone-chassis-medium",
    "name": "Medium Drone Chassis",
    "raw": false
  },
  "drone-brain": {
    "id": "drone-brain",
    "name": "Clockwork Brain",
    "raw": false
  },
  "drone-brain-lodite": {
    "id": "drone-brain-lodite",
    "name": "Lodite Brain",
    "raw": false
  },
  "propeller": {
    "id": "propeller",
    "name": "Propeller",
    "raw": false
  },
  "drone-scout": {
    "id": "drone-scout",
    "name": "Clockwork Scout Drone",
    "raw": false
  },
  "drone-sentry": {
    "id": "drone-sentry",
    "name": "Mechanical Sentry",
    "raw": false
  },
  "drone-hauler": {
    "id": "drone-hauler",
    "name": "Steam Hauler",
    "raw": false
  },
  "drone-miner": {
    "id": "drone-miner",
    "name": "Mining Drone",
    "raw": false
  },
  "drone-repair": {
    "id": "drone-repair",
    "name": "Repair Drone",
    "raw": false
  },
  "drone-combat": {
    "id": "drone-combat",
    "name": "Combat Drone",
    "raw": false
  },
  "drone-shield": {
    "id": "drone-shield",
    "name": "Shield Drone",
    "raw": false
  },
  "drone-gatherer": {
    "id": "drone-gatherer",
    "name": "Gathering Swarm",
    "raw": false
  },
  "struct-workbench": {
    "id": "struct-workbench",
    "name": "Workbench",
    "raw": false
  },
  "struct-storage-chest": {
    "id": "struct-storage-chest",
    "name": "Storage Chest",
    "raw": false
  },
  "struct-drying-rack": {
    "id": "struct-drying-rack",
    "name": "Drying Rack",
    "raw": false
  },
  "struct-rain-catcher": {
    "id": "struct-rain-catcher",
    "name": "Rain Catcher",
    "raw": false
  },
  "struct-field-forge": {
    "id": "struct-field-forge",
    "name": "Field Forge",
    "raw": false
  },
  "struct-watchtower": {
    "id": "struct-watchtower",
    "name": "Watchtower",
    "raw": false
  },
  "struct-palisade": {
    "id": "struct-palisade",
    "name": "Palisade Wall",
    "raw": false
  },
  "struct-gate": {
    "id": "struct-gate",
    "name": "Palisade Gate",
    "raw": false
  },
  "struct-generator": {
    "id": "struct-generator",
    "name": "Steam Generator",
    "raw": false
  },
  "struct-auto-smelter": {
    "id": "struct-auto-smelter",
    "name": "Automated Smelter",
    "raw": false
  },
  "struct-pipe-section": {
    "id": "struct-pipe-section",
    "name": "Pipe Section",
    "raw": false
  },
  "struct-mech-dock": {
    "id": "struct-mech-dock",
    "name": "Mech Dock",
    "raw": false
  },
  "struct-perimeter-turret": {
    "id": "struct-perimeter-turret",
    "name": "Perimeter Turret",
    "raw": false
  },
  "struct-beacon": {
    "id": "struct-beacon",
    "name": "Beacon",
    "raw": false
  }
};

export const CF_BASE_INV: Record<string, number> = {
  "iron-ore": 20,
  "copper-ore": 20,
  "coal": 20,
  "wood-log": 20,
  "hardwood-log": 20,
  "stone": 20,
  "flint": 20,
  "clay": 20,
  "hide-raw": 20,
  "bone": 20,
  "sinew": 20,
  "animal-fat": 20,
  "herb-green": 20,
  "herb-bitter": 20,
  "herb-fire": 20,
  "plant-fiber": 20,
  "resin": 20,
  "feather": 20,
  "salt": 20,
  "rune-dust": 20,
  "spirit-sap": 20,
  "raw-meat": 20,
  "raw-fish": 20,
  "berries": 20,
  "grain": 20,
  "freshwater": 20,
  "dry-grass": 20,
  "tin-ore": 20,
  "silver-ore": 20,
  "quartz": 20,
  "sulfur": 20,
  "peat": 20,
  "beeswax": 20,
  "crystal-shard": 20,
  "amber": 20,
  "lodite-ore": 20,
  "rubber-sap": 20,
  "iron-ingot": 6,
  "copper-ingot": 6,
  "leather": 6,
  "wood-plank": 6,
  "hardwood-plank": 6,
  "charcoal": 6,
  "rope": 6,
  "cloth": 6,
  "brick": 6,
  "glass": 6,
  "oil": 6,
  "glue": 6,
  "bronze-ingot": 6,
  "silver-ingot": 6,
  "steel-ingot": 6,
  "steel-alloy": 6,
  "tallow": 6,
  "flour": 6,
  "wire-copper": 6,
  "hardened-leather": 6,
  "blast-powder": 6,
  "acid-flask": 6,
  "rubber": 6,
  "lodite-ingot": 6,
  "wood-handle": 3,
  "iron-nails": 3,
  "leather-strip": 3,
  "arrow-shaft": 3,
  "iron-blade": 3,
  "bowstring": 3,
  "iron-plate": 3,
  "copper-tube": 3,
  "hinge": 3,
  "lens": 3,
  "steel-blade": 3,
  "steel-plate": 3,
  "gear-iron": 3,
  "spring-iron": 3,
  "rivet": 3,
  "bearing": 3,
  "piston": 3,
  "valve": 3,
  "boiler": 3,
  "drive-shaft": 3,
  "precision-gear": 3,
  "hydraulic-cylinder": 3,
  "lodite-cell": 3,
  "steam-engine": 3,
  "mech-frame": 3,
  "mech-joint": 3,
  "mech-actuator": 3,
  "control-harness": 3,
  "mech-plating": 3,
  "drone-chassis-small": 3,
  "drone-chassis-medium": 3,
  "drone-brain": 3,
  "drone-brain-lodite": 3,
  "propeller": 3
};

export const CF_RECIPES: CFRecipe[] = [
  {
    "id": "rope",
    "station": "field",
    "tier": 0,
    "outN": 1,
    "inputs": [
      [
        "plant-fiber",
        4
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "bandage",
    "station": "field",
    "tier": 0,
    "outN": 2,
    "inputs": [
      [
        "cloth",
        1
      ],
      [
        "herb-green",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "torch",
    "station": "field",
    "tier": 0,
    "outN": 2,
    "inputs": [
      [
        "wood-log",
        1
      ],
      [
        "cloth",
        1
      ],
      [
        "animal-fat",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "cloth",
    "station": "field",
    "tier": 0,
    "outN": 1,
    "inputs": [
      [
        "plant-fiber",
        3
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "healing-salve",
    "station": "field",
    "tier": 0,
    "outN": 2,
    "inputs": [
      [
        "herb-green",
        2
      ],
      [
        "animal-fat",
        1
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "antidote",
    "station": "field",
    "tier": 0,
    "outN": 1,
    "inputs": [
      [
        "herb-bitter",
        2
      ],
      [
        "salt",
        1
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "trap-snare",
    "station": "field",
    "tier": 0,
    "outN": 1,
    "inputs": [
      [
        "rope",
        1
      ],
      [
        "wood-log",
        1
      ]
    ],
    "concepts": [],
    "origin": "OBSERVED"
  },
  {
    "id": "ration",
    "station": "field",
    "tier": 0,
    "outN": 2,
    "inputs": [
      [
        "hide-raw",
        1
      ],
      [
        "salt",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "wood-handle",
    "station": "field",
    "tier": 1,
    "outN": 2,
    "inputs": [
      [
        "wood-log",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "wood-plank",
    "station": "field",
    "tier": 1,
    "outN": 2,
    "inputs": [
      [
        "wood-log",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "leather-strip",
    "station": "field",
    "tier": 1,
    "outN": 2,
    "inputs": [
      [
        "leather",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "arrow-shaft",
    "station": "field",
    "tier": 1,
    "outN": 4,
    "inputs": [
      [
        "wood-log",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "glue",
    "station": "field",
    "tier": 1,
    "outN": 2,
    "inputs": [
      [
        "bone",
        2
      ],
      [
        "resin",
        1
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "oil",
    "station": "field",
    "tier": 1,
    "outN": 2,
    "inputs": [
      [
        "animal-fat",
        3
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "bowstring",
    "station": "field",
    "tier": 1,
    "outN": 1,
    "inputs": [
      [
        "sinew",
        2
      ],
      [
        "plant-fiber",
        2
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "charcoal",
    "station": "kiln",
    "tier": 2,
    "outN": 3,
    "inputs": [
      [
        "wood-log",
        2
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "brick",
    "station": "kiln",
    "tier": 2,
    "outN": 2,
    "inputs": [
      [
        "clay",
        3
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "glass",
    "station": "kiln",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "stone",
        2
      ],
      [
        "salt",
        1
      ],
      [
        "charcoal",
        1
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "iron-ingot",
    "station": "smelter",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "iron-ore",
        3
      ],
      [
        "coal",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "copper-ingot",
    "station": "smelter",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "copper-ore",
        3
      ],
      [
        "charcoal",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "leather",
    "station": "tannery",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "hide-raw",
        2
      ],
      [
        "salt",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "hardwood-plank",
    "station": "sawmill",
    "tier": 2,
    "outN": 2,
    "inputs": [
      [
        "hardwood-log",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "iron-nails",
    "station": "smithy",
    "tier": 2,
    "outN": 8,
    "inputs": [
      [
        "iron-ingot",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "iron-blade",
    "station": "smithy",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "iron-ingot",
        2
      ],
      [
        "coal",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "iron-dagger",
    "station": "smithy",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "iron-blade",
        1
      ],
      [
        "leather-strip",
        1
      ],
      [
        "wood-handle",
        1
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — VILLAGE SMITH"
  },
  {
    "id": "iron-sword",
    "station": "smithy",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "iron-blade",
        2
      ],
      [
        "leather-strip",
        2
      ],
      [
        "wood-handle",
        1
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — VILLAGE SMITH"
  },
  {
    "id": "iron-axe",
    "station": "smithy",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "iron-ingot",
        2
      ],
      [
        "wood-handle",
        1
      ],
      [
        "leather-strip",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "hunting-bow",
    "station": "workshop",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "hardwood-plank",
        2
      ],
      [
        "bowstring",
        1
      ],
      [
        "leather-strip",
        1
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — HUNTER"
  },
  {
    "id": "wooden-shield",
    "station": "workshop",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "wood-plank",
        3
      ],
      [
        "iron-nails",
        4
      ],
      [
        "leather-strip",
        2
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "leather-armor",
    "station": "tannery",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "leather",
        4
      ],
      [
        "sinew",
        2
      ],
      [
        "iron-nails",
        2
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — TANNER"
  },
  {
    "id": "hide-cloak",
    "station": "tannery",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "leather",
        2
      ],
      [
        "cloth",
        2
      ],
      [
        "sinew",
        1
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "fire-bomb",
    "station": "workshop",
    "tier": 2,
    "outN": 2,
    "inputs": [
      [
        "oil",
        1
      ],
      [
        "herb-fire",
        1
      ],
      [
        "clay",
        1
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "smoke-bomb",
    "station": "workshop",
    "tier": 2,
    "outN": 2,
    "inputs": [
      [
        "charcoal",
        2
      ],
      [
        "cloth",
        1
      ],
      [
        "clay",
        1
      ]
    ],
    "concepts": [],
    "origin": "REVERSE-ENGINEERED"
  },
  {
    "id": "iron-dagger-runed",
    "station": "smithy",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "iron-dagger",
        1
      ],
      [
        "rune-dust",
        2
      ],
      [
        "spirit-sap",
        1
      ]
    ],
    "concepts": [
      [
        "inscription",
        1
      ],
      [
        "heat-treatment",
        2
      ]
    ],
    "origin": "OBSERVED"
  },
  {
    "id": "fire-starter",
    "station": "field",
    "tier": 0,
    "outN": 1,
    "inputs": [
      [
        "flint",
        1
      ],
      [
        "dry-grass",
        2
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "campfire",
    "station": "field",
    "tier": 0,
    "outN": 1,
    "inputs": [
      [
        "wood-log",
        3
      ],
      [
        "stone",
        3
      ],
      [
        "fire-starter",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "waterskin",
    "station": "field",
    "tier": 0,
    "outN": 1,
    "inputs": [
      [
        "hide-raw",
        1
      ],
      [
        "sinew",
        1
      ],
      [
        "resin",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "bedroll",
    "station": "field",
    "tier": 0,
    "outN": 1,
    "inputs": [
      [
        "hide-raw",
        2
      ],
      [
        "dry-grass",
        4
      ],
      [
        "rope",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "stone-knife",
    "station": "field",
    "tier": 0,
    "outN": 1,
    "inputs": [
      [
        "flint",
        2
      ],
      [
        "wood-handle",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "cooked-meat",
    "station": "campfire",
    "tier": 1,
    "outN": 2,
    "inputs": [
      [
        "raw-meat",
        2
      ],
      [
        "fire-starter",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "grilled-fish",
    "station": "campfire",
    "tier": 1,
    "outN": 2,
    "inputs": [
      [
        "raw-fish",
        2
      ],
      [
        "fire-starter",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "purified-water",
    "station": "campfire",
    "tier": 1,
    "outN": 2,
    "inputs": [
      [
        "freshwater",
        2
      ],
      [
        "charcoal",
        1
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "lean-to",
    "station": "field",
    "tier": 1,
    "outN": 1,
    "inputs": [
      [
        "wood-log",
        4
      ],
      [
        "rope",
        2
      ],
      [
        "plant-fiber",
        4
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "fishing-rod",
    "station": "field",
    "tier": 1,
    "outN": 1,
    "inputs": [
      [
        "wood-log",
        2
      ],
      [
        "sinew",
        2
      ],
      [
        "bone",
        1
      ]
    ],
    "concepts": [],
    "origin": "OBSERVED"
  },
  {
    "id": "skinning-knife",
    "station": "field",
    "tier": 1,
    "outN": 1,
    "inputs": [
      [
        "flint",
        1
      ],
      [
        "bone",
        1
      ],
      [
        "leather-strip",
        1
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "crude-shovel",
    "station": "field",
    "tier": 1,
    "outN": 1,
    "inputs": [
      [
        "wood-plank",
        1
      ],
      [
        "wood-handle",
        1
      ],
      [
        "rope",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "pouch",
    "station": "field",
    "tier": 1,
    "outN": 1,
    "inputs": [
      [
        "leather",
        1
      ],
      [
        "sinew",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "tallow",
    "station": "campfire",
    "tier": 1,
    "outN": 2,
    "inputs": [
      [
        "animal-fat",
        3
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "bread",
    "station": "campfire",
    "tier": 1,
    "outN": 3,
    "inputs": [
      [
        "flour",
        2
      ],
      [
        "freshwater",
        1
      ],
      [
        "salt",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "flour",
    "station": "workshop",
    "tier": 2,
    "outN": 2,
    "inputs": [
      [
        "grain",
        3
      ],
      [
        "stone",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "stew",
    "station": "cookpot",
    "tier": 2,
    "outN": 2,
    "inputs": [
      [
        "cooked-meat",
        1
      ],
      [
        "herb-green",
        1
      ],
      [
        "salt",
        1
      ],
      [
        "freshwater",
        1
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "bronze-ingot",
    "station": "smelter",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "copper-ore",
        2
      ],
      [
        "tin-ore",
        1
      ],
      [
        "charcoal",
        1
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "silver-ingot",
    "station": "smelter",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "silver-ore",
        3
      ],
      [
        "charcoal",
        1
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — BERGFOLK MINER"
  },
  {
    "id": "wire-copper",
    "station": "smithy",
    "tier": 2,
    "outN": 3,
    "inputs": [
      [
        "copper-ingot",
        1
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "iron-plate",
    "station": "smithy",
    "tier": 2,
    "outN": 2,
    "inputs": [
      [
        "iron-ingot",
        2
      ],
      [
        "coal",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "copper-tube",
    "station": "smithy",
    "tier": 2,
    "outN": 2,
    "inputs": [
      [
        "copper-ingot",
        1
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "hinge",
    "station": "smithy",
    "tier": 2,
    "outN": 2,
    "inputs": [
      [
        "iron-ingot",
        1
      ],
      [
        "iron-nails",
        2
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "lens",
    "station": "kiln",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "glass",
        2
      ],
      [
        "iron-plate",
        1
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "pickaxe",
    "station": "smithy",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "iron-ingot",
        2
      ],
      [
        "wood-handle",
        1
      ],
      [
        "leather-strip",
        1
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — BERGFOLK MINER"
  },
  {
    "id": "iron-shovel",
    "station": "smithy",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "iron-ingot",
        1
      ],
      [
        "wood-handle",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "backpack",
    "station": "tannery",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "leather",
        3
      ],
      [
        "rope",
        2
      ],
      [
        "iron-nails",
        4
      ],
      [
        "wood-plank",
        2
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "lantern",
    "station": "smithy",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "iron-plate",
        2
      ],
      [
        "glass",
        1
      ],
      [
        "tallow",
        1
      ],
      [
        "wire-copper",
        1
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "compass",
    "station": "workshop",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "iron-ingot",
        1
      ],
      [
        "glass",
        1
      ],
      [
        "copper-ingot",
        1
      ],
      [
        "rune-dust",
        1
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — NAVIGATOR"
  },
  {
    "id": "spyglass",
    "station": "workshop",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "copper-tube",
        2
      ],
      [
        "lens",
        2
      ],
      [
        "leather-strip",
        1
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — NAVIGATOR"
  },
  {
    "id": "barrel",
    "station": "workshop",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "wood-plank",
        4
      ],
      [
        "iron-nails",
        4
      ],
      [
        "hinge",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "tent",
    "station": "workshop",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "cloth",
        4
      ],
      [
        "rope",
        3
      ],
      [
        "wood-log",
        4
      ],
      [
        "iron-nails",
        4
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "iron-chainmail",
    "station": "smithy",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "wire-copper",
        2
      ],
      [
        "iron-ingot",
        4
      ],
      [
        "leather",
        2
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — VILLAGE SMITH"
  },
  {
    "id": "steel-ingot",
    "station": "smelter",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "iron-ingot",
        2
      ],
      [
        "coal",
        2
      ],
      [
        "charcoal",
        1
      ]
    ],
    "concepts": [
      [
        "alloys",
        2
      ],
      [
        "heat-treatment",
        2
      ]
    ],
    "origin": "TAUGHT — MASTER SMITH"
  },
  {
    "id": "hardened-leather",
    "station": "tannery",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "leather",
        2
      ],
      [
        "beeswax",
        1
      ],
      [
        "resin",
        1
      ]
    ],
    "concepts": [
      [
        "tanning",
        2
      ]
    ],
    "origin": "EXPERIMENT"
  },
  {
    "id": "blast-powder",
    "station": "workshop",
    "tier": 3,
    "outN": 2,
    "inputs": [
      [
        "sulfur",
        2
      ],
      [
        "charcoal",
        2
      ],
      [
        "salt",
        1
      ]
    ],
    "concepts": [
      [
        "combustion",
        2
      ]
    ],
    "origin": "EXPERIMENT"
  },
  {
    "id": "acid-flask",
    "station": "workshop",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "sulfur",
        1
      ],
      [
        "freshwater",
        1
      ],
      [
        "glass",
        1
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "steel-blade",
    "station": "smithy",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "steel-ingot",
        2
      ],
      [
        "coal",
        1
      ]
    ],
    "concepts": [
      [
        "sharpening",
        2
      ]
    ],
    "origin": "TAUGHT — MASTER SMITH"
  },
  {
    "id": "steel-plate",
    "station": "smithy",
    "tier": 3,
    "outN": 2,
    "inputs": [
      [
        "steel-ingot",
        2
      ],
      [
        "coal",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "gear-iron",
    "station": "smithy",
    "tier": 3,
    "outN": 2,
    "inputs": [
      [
        "iron-ingot",
        2
      ],
      [
        "charcoal",
        1
      ]
    ],
    "concepts": [
      [
        "rotation",
        2
      ]
    ],
    "origin": "OBSERVED"
  },
  {
    "id": "spring-iron",
    "station": "smithy",
    "tier": 3,
    "outN": 2,
    "inputs": [
      [
        "iron-ingot",
        1
      ],
      [
        "wire-copper",
        1
      ]
    ],
    "concepts": [
      [
        "tension",
        2
      ]
    ],
    "origin": "OBSERVED"
  },
  {
    "id": "rivet",
    "station": "smithy",
    "tier": 3,
    "outN": 8,
    "inputs": [
      [
        "steel-ingot",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "bearing",
    "station": "smithy",
    "tier": 3,
    "outN": 2,
    "inputs": [
      [
        "bronze-ingot",
        1
      ],
      [
        "oil",
        1
      ]
    ],
    "concepts": [
      [
        "bearings",
        1
      ]
    ],
    "origin": "OBSERVED"
  },
  {
    "id": "steel-sword",
    "station": "smithy",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "steel-blade",
        2
      ],
      [
        "hardwood-plank",
        1
      ],
      [
        "leather-strip",
        2
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — MASTER SMITH"
  },
  {
    "id": "steel-plate-armor",
    "station": "smithy",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "steel-plate",
        4
      ],
      [
        "hardened-leather",
        2
      ],
      [
        "rivet",
        6
      ],
      [
        "hinge",
        2
      ]
    ],
    "concepts": [
      [
        "heat-treatment",
        3
      ]
    ],
    "origin": "TAUGHT — MASTER SMITH"
  },
  {
    "id": "crossbow",
    "station": "workshop",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "steel-blade",
        1
      ],
      [
        "spring-iron",
        1
      ],
      [
        "hardwood-plank",
        2
      ],
      [
        "bowstring",
        1
      ],
      [
        "gear-iron",
        1
      ]
    ],
    "concepts": [],
    "origin": "REVERSE-ENGINEERED"
  },
  {
    "id": "mining-charge",
    "station": "workshop",
    "tier": 3,
    "outN": 2,
    "inputs": [
      [
        "blast-powder",
        2
      ],
      [
        "clay",
        1
      ],
      [
        "rope",
        1
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — BERGFOLK MINER"
  },
  {
    "id": "steel-alloy",
    "station": "foundry",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "steel-ingot",
        2
      ],
      [
        "copper-ingot",
        1
      ],
      [
        "charcoal",
        2
      ]
    ],
    "concepts": [
      [
        "alloys",
        3
      ],
      [
        "heat-treatment",
        3
      ]
    ],
    "origin": "EXPERIMENT"
  },
  {
    "id": "rubber",
    "station": "foundry",
    "tier": 4,
    "outN": 2,
    "inputs": [
      [
        "rubber-sap",
        3
      ],
      [
        "sulfur",
        1
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "lodite-ingot",
    "station": "foundry",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "lodite-ore",
        3
      ],
      [
        "coal",
        2
      ],
      [
        "acid-flask",
        1
      ]
    ],
    "concepts": [
      [
        "alloys",
        2
      ]
    ],
    "origin": "TAUGHT — DEEP BERGFOLK ELDER"
  },
  {
    "id": "precision-gear",
    "station": "engine-works",
    "tier": 4,
    "outN": 2,
    "inputs": [
      [
        "steel-ingot",
        1
      ],
      [
        "oil",
        1
      ]
    ],
    "concepts": [
      [
        "precision",
        1
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "piston",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "steel-plate",
        1
      ],
      [
        "bronze-ingot",
        1
      ],
      [
        "rubber",
        1
      ],
      [
        "oil",
        1
      ]
    ],
    "concepts": [],
    "origin": "OBSERVED"
  },
  {
    "id": "valve",
    "station": "engine-works",
    "tier": 4,
    "outN": 2,
    "inputs": [
      [
        "bronze-ingot",
        1
      ],
      [
        "spring-iron",
        1
      ],
      [
        "rubber",
        1
      ]
    ],
    "concepts": [],
    "origin": "OBSERVED"
  },
  {
    "id": "boiler",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "steel-plate",
        4
      ],
      [
        "copper-tube",
        4
      ],
      [
        "rivet",
        8
      ],
      [
        "valve",
        2
      ]
    ],
    "concepts": [
      [
        "pressure",
        1
      ],
      [
        "sealing",
        2
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "drive-shaft",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "steel-alloy",
        2
      ],
      [
        "bearing",
        2
      ],
      [
        "precision-gear",
        1
      ]
    ],
    "concepts": [
      [
        "rotation",
        3
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "hydraulic-cylinder",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "steel-plate",
        2
      ],
      [
        "piston",
        1
      ],
      [
        "rubber",
        1
      ],
      [
        "oil",
        2
      ]
    ],
    "concepts": [
      [
        "pressure",
        2
      ]
    ],
    "origin": "INNATE"
  },
  {
    "id": "lodite-cell",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "lodite-ingot",
        2
      ],
      [
        "wire-copper",
        3
      ],
      [
        "glass",
        1
      ],
      [
        "crystal-shard",
        1
      ]
    ],
    "concepts": [
      [
        "conduit-craft",
        2
      ]
    ],
    "origin": "TAUGHT — DEEP BERGFOLK ELDER"
  },
  {
    "id": "steam-engine",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "boiler",
        1
      ],
      [
        "piston",
        2
      ],
      [
        "drive-shaft",
        1
      ],
      [
        "valve",
        2
      ],
      [
        "gear-iron",
        2
      ]
    ],
    "concepts": [
      [
        "pressure",
        2
      ],
      [
        "gear-train",
        2
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "steam-hammer",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "steel-alloy",
        2
      ],
      [
        "piston",
        1
      ],
      [
        "wood-handle",
        1
      ],
      [
        "valve",
        1
      ],
      [
        "rubber",
        1
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "hydraulic-shield",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "steel-plate",
        3
      ],
      [
        "hydraulic-cylinder",
        1
      ],
      [
        "rubber",
        1
      ],
      [
        "rivet",
        4
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "mech-plating",
    "station": "foundry",
    "tier": 4,
    "outN": 2,
    "inputs": [
      [
        "steel-alloy",
        3
      ],
      [
        "rivet",
        6
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "mech-joint",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "steel-alloy",
        1
      ],
      [
        "bearing",
        2
      ],
      [
        "hydraulic-cylinder",
        1
      ],
      [
        "precision-gear",
        1
      ]
    ],
    "concepts": [
      [
        "precision",
        2
      ],
      [
        "gear-train",
        2
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "mech-actuator",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "hydraulic-cylinder",
        1
      ],
      [
        "spring-iron",
        2
      ],
      [
        "lodite-cell",
        1
      ],
      [
        "wire-copper",
        2
      ]
    ],
    "concepts": [
      [
        "pressure",
        3
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "control-harness",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "hardened-leather",
        3
      ],
      [
        "wire-copper",
        4
      ],
      [
        "lodite-cell",
        1
      ],
      [
        "crystal-shard",
        2
      ],
      [
        "spring-iron",
        2
      ]
    ],
    "concepts": [
      [
        "conduit-craft",
        3
      ],
      [
        "precision",
        2
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "mech-frame",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "steel-alloy",
        6
      ],
      [
        "mech-joint",
        4
      ],
      [
        "mech-plating",
        4
      ],
      [
        "rivet",
        12
      ],
      [
        "drive-shaft",
        2
      ]
    ],
    "concepts": [
      [
        "gear-train",
        3
      ],
      [
        "precision",
        3
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "mech-scout",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "mech-frame",
        1
      ],
      [
        "steam-engine",
        1
      ],
      [
        "control-harness",
        1
      ],
      [
        "mech-actuator",
        2
      ],
      [
        "lodite-cell",
        1
      ]
    ],
    "concepts": [
      [
        "gear-train",
        3
      ],
      [
        "pressure",
        3
      ],
      [
        "precision",
        3
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "mech-warden",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "mech-frame",
        1
      ],
      [
        "steam-engine",
        1
      ],
      [
        "control-harness",
        1
      ],
      [
        "mech-actuator",
        4
      ],
      [
        "mech-plating",
        4
      ],
      [
        "lodite-cell",
        2
      ]
    ],
    "concepts": [
      [
        "gear-train",
        3
      ],
      [
        "pressure",
        3
      ],
      [
        "precision",
        3
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "mech-arm-hammer",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "steel-alloy",
        3
      ],
      [
        "mech-actuator",
        1
      ],
      [
        "hydraulic-cylinder",
        2
      ],
      [
        "mech-joint",
        1
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "mech-arm-drill",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "steel-alloy",
        2
      ],
      [
        "precision-gear",
        3
      ],
      [
        "mech-actuator",
        1
      ],
      [
        "drive-shaft",
        1
      ],
      [
        "bearing",
        2
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "mech-shield-module",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "mech-plating",
        3
      ],
      [
        "hydraulic-cylinder",
        2
      ],
      [
        "spring-iron",
        2
      ],
      [
        "lodite-cell",
        1
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "struct-workbench",
    "station": "workshop",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "wood-plank",
        4
      ],
      [
        "iron-nails",
        6
      ],
      [
        "wood-log",
        2
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "struct-storage-chest",
    "station": "workshop",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "wood-plank",
        3
      ],
      [
        "iron-nails",
        4
      ],
      [
        "hinge",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "struct-drying-rack",
    "station": "field",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "wood-log",
        3
      ],
      [
        "rope",
        2
      ],
      [
        "iron-nails",
        2
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "struct-rain-catcher",
    "station": "field",
    "tier": 2,
    "outN": 1,
    "inputs": [
      [
        "cloth",
        2
      ],
      [
        "wood-log",
        2
      ],
      [
        "rope",
        1
      ],
      [
        "barrel",
        1
      ]
    ],
    "concepts": [],
    "origin": "MEMORY"
  },
  {
    "id": "struct-field-forge",
    "station": "smithy",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "brick",
        6
      ],
      [
        "iron-plate",
        4
      ],
      [
        "iron-nails",
        8
      ],
      [
        "copper-tube",
        2
      ]
    ],
    "concepts": [
      [
        "heat-treatment",
        2
      ]
    ],
    "origin": "TAUGHT — MASTER SMITH"
  },
  {
    "id": "struct-watchtower",
    "station": "workshop",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "wood-plank",
        8
      ],
      [
        "iron-nails",
        8
      ],
      [
        "rope",
        3
      ],
      [
        "wood-log",
        4
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "struct-palisade",
    "station": "field",
    "tier": 3,
    "outN": 2,
    "inputs": [
      [
        "wood-log",
        4
      ],
      [
        "rope",
        1
      ],
      [
        "iron-nails",
        4
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "struct-gate",
    "station": "workshop",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "wood-plank",
        4
      ],
      [
        "hinge",
        2
      ],
      [
        "iron-nails",
        6
      ],
      [
        "rope",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "struct-generator",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "steam-engine",
        1
      ],
      [
        "wire-copper",
        4
      ],
      [
        "steel-plate",
        4
      ],
      [
        "rivet",
        8
      ],
      [
        "lodite-cell",
        1
      ]
    ],
    "concepts": [
      [
        "pressure",
        2
      ],
      [
        "gear-train",
        2
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "struct-auto-smelter",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "brick",
        8
      ],
      [
        "steel-plate",
        4
      ],
      [
        "gear-iron",
        2
      ],
      [
        "copper-tube",
        4
      ],
      [
        "valve",
        2
      ]
    ],
    "concepts": [
      [
        "heat-treatment",
        3
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "struct-pipe-section",
    "station": "engine-works",
    "tier": 4,
    "outN": 3,
    "inputs": [
      [
        "copper-tube",
        2
      ],
      [
        "rubber",
        1
      ],
      [
        "rivet",
        2
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "struct-mech-dock",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "steel-alloy",
        6
      ],
      [
        "hydraulic-cylinder",
        2
      ],
      [
        "wire-copper",
        6
      ],
      [
        "lodite-cell",
        2
      ],
      [
        "rivet",
        12
      ],
      [
        "struct-pipe-section",
        3
      ]
    ],
    "concepts": [
      [
        "precision",
        3
      ],
      [
        "pressure",
        3
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "struct-perimeter-turret",
    "station": "engine-works",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "steel-plate",
        3
      ],
      [
        "gear-iron",
        2
      ],
      [
        "spring-iron",
        2
      ],
      [
        "lodite-cell",
        1
      ],
      [
        "drone-brain",
        1
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "struct-beacon",
    "station": "engine-works",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "lodite-cell",
        2
      ],
      [
        "crystal-shard",
        3
      ],
      [
        "wire-copper",
        4
      ],
      [
        "steel-plate",
        2
      ],
      [
        "lens",
        1
      ]
    ],
    "concepts": [
      [
        "conduit-craft",
        3
      ],
      [
        "resonance",
        2
      ]
    ],
    "origin": "TAUGHT — DEEP BERGFOLK ELDER"
  },
  {
    "id": "drone-brain",
    "station": "engine-works",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "precision-gear",
        3
      ],
      [
        "spring-iron",
        2
      ],
      [
        "wire-copper",
        2
      ],
      [
        "bronze-ingot",
        1
      ]
    ],
    "concepts": [
      [
        "gear-train",
        2
      ],
      [
        "precision",
        2
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "drone-brain-lodite",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "drone-brain",
        1
      ],
      [
        "lodite-cell",
        1
      ],
      [
        "crystal-shard",
        2
      ],
      [
        "wire-copper",
        3
      ]
    ],
    "concepts": [
      [
        "conduit-craft",
        2
      ],
      [
        "precision",
        3
      ]
    ],
    "origin": "TAUGHT — DEEP BERGFOLK ELDER"
  },
  {
    "id": "propeller",
    "station": "smithy",
    "tier": 3,
    "outN": 2,
    "inputs": [
      [
        "steel-ingot",
        1
      ],
      [
        "bearing",
        1
      ]
    ],
    "concepts": [],
    "origin": "OBSERVED"
  },
  {
    "id": "drone-chassis-small",
    "station": "smithy",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "iron-plate",
        2
      ],
      [
        "gear-iron",
        2
      ],
      [
        "hinge",
        2
      ],
      [
        "rivet",
        4
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "drone-chassis-medium",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "steel-plate",
        3
      ],
      [
        "precision-gear",
        2
      ],
      [
        "hinge",
        2
      ],
      [
        "rivet",
        6
      ],
      [
        "rubber",
        1
      ]
    ],
    "concepts": [],
    "origin": "INNATE"
  },
  {
    "id": "drone-scout",
    "station": "engine-works",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "drone-chassis-small",
        1
      ],
      [
        "drone-brain",
        1
      ],
      [
        "propeller",
        2
      ],
      [
        "lens",
        1
      ],
      [
        "spring-iron",
        2
      ]
    ],
    "concepts": [
      [
        "gear-train",
        2
      ],
      [
        "precision",
        2
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "drone-sentry",
    "station": "engine-works",
    "tier": 3,
    "outN": 1,
    "inputs": [
      [
        "drone-chassis-small",
        1
      ],
      [
        "drone-brain",
        1
      ],
      [
        "spring-iron",
        3
      ],
      [
        "iron-blade",
        1
      ],
      [
        "gear-iron",
        2
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  },
  {
    "id": "drone-hauler",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "drone-chassis-medium",
        1
      ],
      [
        "drone-brain",
        1
      ],
      [
        "piston",
        1
      ],
      [
        "boiler",
        1
      ],
      [
        "bearing",
        2
      ],
      [
        "steel-plate",
        2
      ]
    ],
    "concepts": [
      [
        "pressure",
        2
      ]
    ],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "drone-miner",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "drone-chassis-medium",
        1
      ],
      [
        "drone-brain",
        1
      ],
      [
        "piston",
        1
      ],
      [
        "drive-shaft",
        1
      ],
      [
        "precision-gear",
        2
      ],
      [
        "steel-blade",
        1
      ]
    ],
    "concepts": [
      [
        "gear-train",
        2
      ]
    ],
    "origin": "EXPERIMENT"
  },
  {
    "id": "drone-repair",
    "station": "engine-works",
    "tier": 4,
    "outN": 1,
    "inputs": [
      [
        "drone-chassis-small",
        1
      ],
      [
        "drone-brain",
        1
      ],
      [
        "propeller",
        2
      ],
      [
        "wire-copper",
        3
      ],
      [
        "spring-iron",
        2
      ],
      [
        "oil",
        2
      ]
    ],
    "concepts": [],
    "origin": "TAUGHT — OLD WAR ENGINEER"
  },
  {
    "id": "drone-combat",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "drone-chassis-medium",
        1
      ],
      [
        "drone-brain-lodite",
        1
      ],
      [
        "propeller",
        2
      ],
      [
        "steel-blade",
        2
      ],
      [
        "lodite-cell",
        1
      ],
      [
        "spring-iron",
        2
      ]
    ],
    "concepts": [
      [
        "precision",
        3
      ],
      [
        "gear-train",
        3
      ]
    ],
    "origin": "EXPERIMENT"
  },
  {
    "id": "drone-shield",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "drone-chassis-small",
        1
      ],
      [
        "drone-brain-lodite",
        1
      ],
      [
        "propeller",
        2
      ],
      [
        "lodite-cell",
        2
      ],
      [
        "crystal-shard",
        2
      ],
      [
        "wire-copper",
        3
      ]
    ],
    "concepts": [
      [
        "conduit-craft",
        3
      ]
    ],
    "origin": "TAUGHT — DEEP BERGFOLK ELDER"
  },
  {
    "id": "drone-gatherer",
    "station": "mech-bay",
    "tier": 5,
    "outN": 1,
    "inputs": [
      [
        "drone-chassis-small",
        3
      ],
      [
        "drone-brain-lodite",
        1
      ],
      [
        "propeller",
        6
      ],
      [
        "lodite-cell",
        1
      ],
      [
        "wire-copper",
        4
      ]
    ],
    "concepts": [],
    "origin": "EXPERIMENT"
  }
];

/** No discovery silhouettes in the testbed — every recipe is browsable. */
export const CF_HINTS: CFHint[] = [];

export const CF_PROCS: CFProc[] = [
  {
    "id": "charcoal",
    "name": "Refine Charcoal",
    "station": "kiln",
    "ins": [
      [
        "wood-log",
        2
      ]
    ],
    "outN": 3,
    "dur": 6000
  },
  {
    "id": "brick",
    "name": "Refine Brick",
    "station": "kiln",
    "ins": [
      [
        "clay",
        3
      ]
    ],
    "outN": 2,
    "dur": 6000
  },
  {
    "id": "iron-ingot",
    "name": "Refine Iron Ingot",
    "station": "smelter",
    "ins": [
      [
        "iron-ore",
        3
      ],
      [
        "coal",
        1
      ]
    ],
    "outN": 1,
    "dur": 6000
  },
  {
    "id": "copper-ingot",
    "name": "Refine Copper Ingot",
    "station": "smelter",
    "ins": [
      [
        "copper-ore",
        3
      ],
      [
        "charcoal",
        1
      ]
    ],
    "outN": 1,
    "dur": 6000
  },
  {
    "id": "leather",
    "name": "Refine Leather",
    "station": "tannery",
    "ins": [
      [
        "hide-raw",
        2
      ],
      [
        "salt",
        1
      ]
    ],
    "outN": 1,
    "dur": 6000
  },
  {
    "id": "leather-armor",
    "name": "Refine Leather Armor",
    "station": "tannery",
    "ins": [
      [
        "leather",
        4
      ],
      [
        "sinew",
        2
      ],
      [
        "iron-nails",
        2
      ]
    ],
    "outN": 1,
    "dur": 6000
  }
];

export const CF_REFINE_BAYS: CFRefineBay[] = [
  {
    "station": "kiln",
    "label": "BAY 1 · KILN"
  },
  {
    "station": "smelter",
    "label": "BAY 2 · SMELTER"
  },
  {
    "station": "tannery",
    "label": "BAY 3 · TANNERY"
  }
];

export const CF_LOCKED_PROCS: CFLockedProc[] = [];

export const CF_STATIONS: Record<string, string> = {
  "field": "FIELD KIT",
  "kiln": "KILN",
  "smelter": "SMELTER",
  "tannery": "TANNERY",
  "sawmill": "SAWMILL",
  "smithy": "SMITHY",
  "workshop": "WORKSHOP",
  "campfire": "CAMPFIRE",
  "cookpot": "COOKPOT",
  "foundry": "FOUNDRY",
  "engine-works": "ENGINE WORKS",
  "mech-bay": "MECH BAY"
};

export const CF_LOCS: CFLoc[] = [
  {
    "id": "field",
    "label": "FIELD KIT",
    "tier": 3
  },
  {
    "id": "kiln",
    "label": "KILN",
    "tier": 3
  },
  {
    "id": "smelter",
    "label": "SMELTER",
    "tier": 3
  },
  {
    "id": "tannery",
    "label": "TANNERY",
    "tier": 3
  },
  {
    "id": "sawmill",
    "label": "SAWMILL",
    "tier": 3
  },
  {
    "id": "smithy",
    "label": "SMITHY",
    "tier": 3
  },
  {
    "id": "workshop",
    "label": "WORKSHOP",
    "tier": 3
  },
  {
    "id": "campfire",
    "label": "CAMPFIRE",
    "tier": 3
  },
  {
    "id": "cookpot",
    "label": "COOKPOT",
    "tier": 3
  },
  {
    "id": "foundry",
    "label": "FOUNDRY",
    "tier": 3
  },
  {
    "id": "engine-works",
    "label": "ENGINE WORKS",
    "tier": 3
  },
  {
    "id": "mech-bay",
    "label": "MECH BAY",
    "tier": 3
  }
];

export const CF_DEFAULT_AT_IDX = 0;

export const CF_TRAY_POOL: CFPoolEntry[] = [
  {
    "id": "tp-c-heat-treatment",
    "kind": "concept",
    "ref": "heat-treatment"
  },
  {
    "id": "tp-c-friction",
    "kind": "concept",
    "ref": "friction"
  },
  {
    "id": "tp-c-tension",
    "kind": "concept",
    "ref": "tension"
  },
  {
    "id": "tp-c-rotation",
    "kind": "concept",
    "ref": "rotation"
  },
  {
    "id": "tp-c-bearings",
    "kind": "concept",
    "ref": "bearings"
  },
  {
    "id": "tp-c-leverage",
    "kind": "concept",
    "ref": "leverage"
  },
  {
    "id": "tp-c-joinery",
    "kind": "concept",
    "ref": "joinery"
  },
  {
    "id": "tp-c-tanning",
    "kind": "concept",
    "ref": "tanning"
  },
  {
    "id": "tp-m-iron-ore",
    "kind": "material",
    "ref": "iron-ore"
  },
  {
    "id": "tp-m-copper-ore",
    "kind": "material",
    "ref": "copper-ore"
  },
  {
    "id": "tp-m-coal",
    "kind": "material",
    "ref": "coal"
  },
  {
    "id": "tp-m-wood-log",
    "kind": "material",
    "ref": "wood-log"
  },
  {
    "id": "tp-m-hardwood-log",
    "kind": "material",
    "ref": "hardwood-log"
  },
  {
    "id": "tp-m-stone",
    "kind": "material",
    "ref": "stone"
  },
  {
    "id": "tp-m-flint",
    "kind": "material",
    "ref": "flint"
  },
  {
    "id": "tp-m-clay",
    "kind": "material",
    "ref": "clay"
  },
  {
    "id": "tp-r-rope",
    "kind": "recipe",
    "ref": "rope"
  },
  {
    "id": "tp-r-bandage",
    "kind": "recipe",
    "ref": "bandage"
  },
  {
    "id": "tp-r-torch",
    "kind": "recipe",
    "ref": "torch"
  }
];

export const CF_DEFAULT_TRAY: (string | null)[] = [
  "tp-c-heat-treatment",
  "tp-m-iron-ore",
  null,
  null,
  null
];

export const CF_REAL_DISCOVERIES: CFDiscovery[] = [
  {
    "kind": "NEW RECIPE UNLOCKED",
    "title": "Rune Capacitor Mk II",
    "desc": "Resonance and conduit grooves click into place — a capacitor that drinks straight from the ley."
  },
  {
    "kind": "CONCEPT DEEPENED",
    "title": "Conduit Craft → Rank 2",
    "desc": "Energy follows the grooves you cut for it. Wider inlays, cleaner flow."
  },
  {
    "kind": "NEW RECIPE UNLOCKED",
    "title": "Glowcap Signal Torch",
    "desc": "Spores pulse in patterns — a light that speaks in code across the dark between worlds."
  }
];

export const CF_FALSE_DISCOVERIES: CFDiscovery[] = [
  {
    "kind": "NEW RECIPE UNLOCKED",
    "title": "Resonant Ampoule",
    "desc": "Quartz hum sealed in fermented catalyst. Surely this stores leyline charge for days."
  },
  {
    "kind": "CONCEPT DEEPENED",
    "title": "Ferro-Symbiosis → Rank 1",
    "desc": "Metal remembers what fungus teaches it. Obvious, in hindsight."
  },
  {
    "kind": "NEW RECIPE UNLOCKED",
    "title": "Mycelic Battery",
    "desc": "Woven fiber cells, damp with resin — they should hold a charge. They must."
  }
];

export function cfTitle(id: string): string {
  return String(id).split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

/** In-memory testbed state (mirrors the design tool's window.CW). Not persisted. */
export class CraftState {
  private catById = new Map(CF_CATS.map(c => [c.id, c]));
  private conceptById = new Map(CF_CONCEPTS.map(c => [c.id, c]));
  inv: Record<string, number> = { ...CF_BASE_INV };
  rankDelta: Record<string, number> = {};
  tray: (string | null)[] = [...CF_DEFAULT_TRAY];
  discovered = new Set<string>();
  mindProgress = 34;
  insights = 12;
  atIdx = CF_DEFAULT_AT_IDX;

  cat(id: string): CFCategory | undefined { return this.catById.get(id); }
  concept(id: string): CFConcept | undefined { return this.conceptById.get(id); }
  rank(id: string): number {
    const c = this.conceptById.get(id);
    if (!c) return 0;
    return Math.min(c.ranks, c.rank + (this.rankDelta[id] || 0));
  }
  rankUp(id: string): void { this.rankDelta[id] = (this.rankDelta[id] || 0) + 1; }
  prereqsMet(c: CFConcept): boolean {
    return (c.requires || []).every(q => { const [id, lv] = q.split(':'); return this.rank(id) >= +lv; });
  }
  conceptState(c: CFConcept): 'mastered' | 'unlocked' | 'available' | 'locked' {
    const r = this.rank(c.id);
    if (r >= c.ranks) return 'mastered';
    if (r > 0) return 'unlocked';
    return this.prereqsMet(c) ? 'available' : 'locked';
  }
  invAdd(delta: Record<string, number>): void { for (const k in delta) this.inv[k] = (this.inv[k] || 0) + delta[k]; }
  trayAdd(id: string): boolean {
    const i = this.tray.findIndex(x => !x);
    if (i < 0) return false;
    if (this.tray.includes(id)) return true;
    this.tray[i] = id;
    return true;
  }
}
