// types.ts — the canonical data model. THIS is the source of truth.
//
// Core principle of the whole project: a structured simulation is canon; the
// LLM (later) is only a renderer. So these types must capture every fact a
// chronicler would need, with zero prose. Prose is derived, never stored.

// ---------------------------------------------------------------------------
// Primitive aliases — string IDs everywhere so cross-references are explicit.
// ---------------------------------------------------------------------------
export type CharId = string;
export type DynastyId = string;
export type ProvinceId = string;
export type TitleId = string;

export type Sex = "male" | "female";

// ---------------------------------------------------------------------------
// Drives — the motivational substrate. Each is 0..1. Goals are generated by
// reading drives against the world state (claims, scarcity, rivalries), so a
// character's personality is just this vector plus their circumstances.
// ---------------------------------------------------------------------------
export interface Drives {
  ambition: number; // want titles, power, expansion
  greed: number; // want wealth, resources
  vengeance: number; // act on grudges
  piety: number; // restraint; legitimacy-seeking
  lust: number; // marriage / heirs (kept light in v1)
  fear: number; // risk aversion / pre-emption
}

// ---------------------------------------------------------------------------
// Claim — a (possibly weak) right to a title. The engine of multigenerational
// war: succession losers are minted weak claims, which become their children's
// SEIZE_TITLE goals decades later.
// ---------------------------------------------------------------------------
export interface Claim {
  titleId: TitleId;
  strength: "strong" | "weak";
  basis: string; // human-readable origin, e.g. "passed over in 1183"
  year: number; // when the claim arose
}

// A grudge: minted when a scheme against someone is discovered, or a claim is
// denied. Feeds future vengeance-driven goals.
export interface Grudge {
  targetId: CharId;
  reason: string;
  year: number;
}

export interface Character {
  id: CharId;
  name: string;
  sex: Sex;
  dynastyId: DynastyId;
  birthYear: number;
  deathYear: number | null;
  alive: boolean;
  causeOfDeath: string | null;

  // Family graph.
  fatherId: CharId | null;
  motherId: CharId | null;
  spouseId: CharId | null;
  childrenIds: CharId[];

  // Where the character resides / is seated (used by plague + famine).
  provinceId: ProvinceId;

  // Personality + accumulated history.
  drives: Drives;
  claims: Claim[];
  grudges: Grudge[];

  // Opinion of other characters, -100..100. Drives recruiting & conspiracy.
  opinion: Record<CharId, number>;

  // Social reputation, observed by others. A known schemer struggles to
  // recruit; this is the seed of the (deferred) perception layer.
  reputation: {
    schemer: number; // 0..1, how known-treacherous they are
    just: number; // 0..1, reputation for fairness
  };

  // Set true once a character has been promoted up from the pops (social
  // mobility / "breakout"). Lets the sifter spotlight low-born risers.
  lowborn: boolean;
}

export interface Dynasty {
  id: DynastyId;
  name: string;
  founderId: CharId;
  extinctYear: number | null; // set when the last member dies
}

// ---------------------------------------------------------------------------
// Geography — provinces with scarcity. Geography gives history a persistent
// grain: carrying capacity caps population, which caps levies and wealth.
// ---------------------------------------------------------------------------
export type Terrain = "plains" | "hills" | "forest" | "coast" | "mountain";

export interface Province {
  id: ProvinceId;
  name: string;
  terrain: Terrain;
  fertility: number; // 0..1 base land quality
  coastal: boolean; // plague spreads faster along coasts
  riverConnected: boolean; // plague spreads along rivers
  neighbors: ProvinceId[]; // connectivity graph (for spread + war reach)

  population: number; // abstract pops (statistical tier)
  titleId: TitleId; // the title that controls this province
}

// ---------------------------------------------------------------------------
// Titles + succession law. Law is mutable (REFORM action) — different laws
// produce different flavours of history.
// ---------------------------------------------------------------------------
export type SuccessionLaw =
  | "primogeniture" // eldest legitimate child
  | "gavelkind" // split among children (approximated: heir + claims to siblings)
  | "elective" // realm picks strongest dynast
  | "seniority"; // eldest member of the dynasty

export type Tier = "county" | "duchy" | "kingdom";

export interface Title {
  id: TitleId;
  name: string;
  tier: Tier;
  law: SuccessionLaw;
  holderId: CharId | null;
  provinceId: ProvinceId; // seat / primary province
  liegeId: TitleId | null; // feudal superior (duchy over county, etc.)
}

// ---------------------------------------------------------------------------
// Goals + schemes — the intentional layer. A goal always has an OBSTACLE;
// the obstacle is what makes it a story. Blocked goals spawn schemes.
// ---------------------------------------------------------------------------
export type GoalType =
  | "SEIZE_TITLE" // press a claim
  | "ELIMINATE_RIVAL" // one person blocks many goals
  | "MARRY" // secure an heir / alliance
  | "EXPAND" // take a neighbouring province
  | "REVENGE" // act on a grudge
  | "REFORM_LAW"; // change succession law in your favour

export interface Goal {
  id: string;
  actorId: CharId;
  type: GoalType;
  targetTitleId: TitleId | null;
  targetCharId: CharId | null; // the obstacle, when it's a person
  priority: number; // 0..1, drives which goals turn into action
}

export type SchemeType = "MURDER" | "USURP" | "REFORM";

export interface Scheme {
  id: string;
  type: SchemeType;
  ownerId: CharId;
  targetCharId: CharId | null;
  targetTitleId: TitleId | null;
  conspirators: CharId[]; // more power, but leaks faster
  progress: number; // 0..1, advances each tick
  secrecy: number; // 0..1, erodes as conspirators join / time passes
  discovered: boolean;
  startYear: number;
}

// ---------------------------------------------------------------------------
// Events — the canonical log. The sifter reads THIS to find storyworthy
// shapes; the renderer turns selected events into prose. Everything that
// happens must leave a structured trace here.
// ---------------------------------------------------------------------------
export type EventType =
  | "BIRTH"
  | "DEATH"
  | "MARRIAGE"
  | "SUCCESSION"
  | "SUCCESSION_CRISIS"
  | "WAR"
  | "SCHEME_HATCHED"
  | "SCHEME_DISCOVERED"
  | "MURDER"
  | "USURP"
  | "REFORM"
  | "FAMINE"
  | "PLAGUE"
  | "HARVEST_FAILURE"
  | "DYNASTY_EXTINCT"
  | "LOWBORN_RISE"
  | "GRUDGE_FORMED";

export interface WorldEvent {
  id: number;
  year: number;
  type: EventType;
  // Structured participants so the sifter & renderer never parse prose.
  actorId: CharId | null;
  targetId: CharId | null;
  titleId: TitleId | null;
  provinceId: ProvinceId | null;
  // A bag of extra structured facts (counts, names, law names, etc.).
  data: Record<string, string | number | boolean>;
  // Filled in by the sifter, not at creation time.
  significance: number;
}
