// types.ts — the canonical data model. THIS is the source of truth.
//
// Core principle of the whole project: a structured simulation is canon; the
// LLM (later) is only a renderer. So these types must capture every fact a
// chronicler would need, with zero prose. Prose is derived, never stored.

// ---------------------------------------------------------------------------
// Primitive aliases — string IDs everywhere so cross-references are explicit.
// ---------------------------------------------------------------------------
export type CharId = string;
export type DynastyId = string;
export type ProvinceId = string;
export type TitleId = string;

export type Sex = "male" | "female";

// ---------------------------------------------------------------------------
// Psyche — the subjective worldview layer.
//
// Every character carries a Psyche. It has two tiers:
//   • biases  — chronic, low-to-moderate perceptual filters; continuous 0..1.
//               Everyone has all of them at varying intensity. Cultural and
//               faith seeds set baselines at birth; life events push them.
//   • distortion — an acute, severe break from reality (paranoid/megalomaniac/
//               zealot). Rare; onset is probabilistic, amplified by inbreeding.
//               Unlike biases, a distortion never self-corrects.
// ---------------------------------------------------------------------------
export type Distortion = "none" | "paranoid" | "megalomaniac" | "zealot";

export type PerceptualBias =
  // Cultural — seeded at birth from the dynasty's culture.
  | "honor_bound"        // slights demand satisfaction; lower REVENGE threshold
  | "fatalist"           // fear drive halved in practice; accepts losses as fate
  | "mercantile"         // reads relationships as transactional
  // Faith — seeded at birth from the dynasty's faith; stacks on cultural seeds.
  | "providential"       // divine attribution; surges after wins, blames enemies after losses
  | "doctrinal"          // faith-based in/out-group hardening; opinion floor vs heretics
  // Experience-acquired — pushed higher by specific life events.
  | "confirmation"       // hears what they want; inflates priority of desired goals
  | "wishful"            // perceives agreement in ambiguity; overestimates support
  | "betrayal_scarred"   // lone-wolf tendencies; no conspirators, high secrecy
  | "grief_locked"       // fear + vengeance amplified after major loss
  | "conqueror_confident"// overestimates own power after major win; resists defeat updates
  // Universal — everyone has a non-zero baseline; no natural ceiling.
  | "sunk_cost"          // abandoning investment feels wrong; escalates losing positions
  | "loss_aversion";     // losses sting ~2× more than equivalent gains feel good

export interface Psyche {
  distortion: Distortion;
  distortionOnsetYear: number | null;
  // All biases in [0,1]. Stored as a flat record so perception.ts can iterate
  // them generically and the type system catches any missing key at compile time.
  biases: Record<PerceptualBias, number>;
  // Computed once at birth from the family graph. Higher = more likely to develop
  // a distortion. 0 for seed characters whose parents aren't in the sim.
  inbreedingCoeff: number;
  // Year of the most recent title loss — gates the post-loss risk-seeking window
  // (loss_aversion drives reckless behaviour for ~5 years after dispossession).
  lastMajorLossYear: number | null;
}

// ---------------------------------------------------------------------------
// Drives — the motivational substrate. Each is 0..1. Goals are generated by
// reading drives against the world state (claims, scarcity, rivalries), so a
// character's personality is just this vector plus their circumstances.
// ---------------------------------------------------------------------------
export interface Drives {
  ambition: number; // want titles, power, expansion
  greed: number; // want wealth, resources
  vengeance: number; // act on grudges
  piety: number; // restraint; legitimacy-seeking
  lust: number; // marriage / heirs (kept light in v1)
  fear: number; // risk aversion / pre-emption
}

// ---------------------------------------------------------------------------
// Claim — a (possibly weak) right to a title. The engine of multigenerational
// war: succession losers are minted weak claims, which become their children's
// SEIZE_TITLE goals decades later.
// ---------------------------------------------------------------------------
export interface Claim {
  titleId: TitleId;
  strength: "strong" | "weak";
  basis: string; // human-readable origin, e.g. "passed over in 1183"
  year: number; // when the claim arose
}

// A grudge: minted when a scheme against someone is discovered, or a claim is
// denied. Feeds future vengeance-driven goals.
export interface Grudge {
  targetId: CharId;
  reason: string;
  year: number;
}

// A temporary peace or permanent defensive pact between two rulers. Truces are
// minted by the engine after wars; alliances form from sustained high opinion.
// Both are stored in World.treaties and queried by the goal and war systems.
export interface Treaty {
  id: string;
  type: "truce" | "alliance";
  partyA: CharId;
  partyB: CharId;
  startYear: number;
  expiresYear: number | null; // null = permanent (alliances)
}

export interface Character {
  id: CharId;
  name: string;
  sex: Sex;
  dynastyId: DynastyId;
  birthYear: number;
  deathYear: number | null;
  alive: boolean;
  causeOfDeath: string | null;

  // Family graph.
  fatherId: CharId | null;
  motherId: CharId | null;
  spouseId: CharId | null;
  childrenIds: CharId[];

  // Where the character resides / is seated (used by plague + famine).
  provinceId: ProvinceId;

  // Personality + accumulated history.
  drives: Drives;
  claims: Claim[];
  grudges: Grudge[];

  // Opinion of other characters, -100..100. Drives recruiting & conspiracy.
  opinion: Record<CharId, number>;

  // Social reputation, observed by others. A known schemer struggles to
  // recruit; reputation feeds the perception layer.
  reputation: {
    schemer: number; // 0..1, how known-treacherous they are
    just: number; // 0..1, reputation for fairness
  };

  // Subjective worldview — the perception/madness layer.
  psyche: Psyche;

  // Set true once a character has been promoted up from the pops (social
  // mobility / "breakout"). Lets the sifter spotlight low-born risers.
  lowborn: boolean;

  // A personal quirk (speech pattern, dress style, bearing) that, if the
  // character becomes a long-established ruler, can propagate into the culture's
  // aesthetic. null = none yet assigned. Set lazily by culture-drift.ts.
  quirk: string | null;

  // --- Magic / leveling layer ------------------------------------------------
  // Only exercised when World.magicEnabled. Kept on every Character (rather than
  // a side-map) so the base sim and the magic sim share one object shape; in
  // base mode these fields are simply initialised once and never touched.
  level: number; // power tier; 1 = an ordinary person
  lifeXp: number; // accumulated XP toward the next level
  charClass: CharClass; // current class — sets martial weight, XP rate, access
  comfort: number; // 0..1 safety+luxury; throttles XP and the will to risk
  ventured: boolean; // transient: sought danger this year (for the chronicle)

  // Optional — named skills earned by surviving specific trials (e.g. "dragon_slayer",
  // "void_walker"). Undefined for characters that never trial-earned anything, so
  // canonHash / base-sim JSON stays byte-identical. Populated only by challenges.ts.
  skills?: string[];

  // --- Personal skill premium & craft lineage --------------------------------
  // Wealth captured by personal skill (master craftsman charges premium). Unlike
  // Dynasty.wealth (dynastic), personalWealth dies with the character unless it
  // passes to an apprentice on death. Populated only when innovation.ts is active
  // (magicEnabled); otherwise stays 0 and is byte-identical to base sim.
  personalWealth: number;

  // A named craft-lineage link: master and apprentices. When the master dies,
  // top apprentice inherits personalWealth + level bump. Enables the "skill dies
  // with you unless you take a student" mechanic that Factor 2 depends on.
  mentorId: CharId | null;
  apprenticeIds: CharId[];
}

// ---------------------------------------------------------------------------
// CultureState — the live, mutable overlay for a culture's current shape.
//
// CultureSpec (in world-spec.ts) is the immutable world bible. CultureState
// is what the sim keeps at runtime: which traits are active by tier, how much
// pressure is building, contested liminal states, and the aesthetic drift left
// by a long-ruling figure. Stored in World.liveCultures.
//
// Two pressure pools (elite/folk) converge at bleedRate = BLEED_BASE × (1 − stratification).
// Traits become CONTESTED when pressure crosses a threshold, then ESTABLISHED after
// `period` years — generational lag models how long real cultural change takes.
// ---------------------------------------------------------------------------
export interface CultureState {
  cultureId: string;
  // Separate pressure pools for lords (titled characters) and commons (untitled).
  elitePressure: Record<string, number>;
  folkPressure:  Record<string, number>;
  // Traits currently established in each tier.
  eliteTraits: Set<string>;
  folkTraits:  Set<string>;
  // Traits in the liminal contested zone (threshold crossed, not yet established).
  // Key: "elite:trait" | "folk:trait" | "elite:abandon:trait" | "folk:abandon:trait".
  contested: Record<string, { tier: "elite" | "folk"; trait: string; years: number; direction: "adopt" | "abandon" }>;
  // 0 = fluid society (tiers bleed freely); 1 = rigidly sealed.
  // Shaped by traits (caste_rigid/slavery push up, meritocracy pulls down) and events.
  stratification: number;
  // Permanent pressure-per-year from significant historical events; never decays.
  legacySeeds: Record<string, number>;
  // Years of continuous contact with neighbouring cultures (for folk contagion).
  contactYears: Record<string, number>;
  // Which (a-vs-b) rift pairs have already fired a CULTURAL_RIFT event.
  activeRifts: Set<string>;
  // Aesthetic drift — surface flavour shaped by a dominant figure's quirks.
  aesthetic: {
    linguisticShift: string | null; // e.g. "sibilant speech", "clipped consonants"
    fashionStyle:    string | null; // e.g. "elaborate fold-style", "austere simplicity"
  };
  // The current dominant figure (highest-tier title holder of this culture).
  establishedFigureId: string | null;
  // Year they became the dominant figure — quirks propagate after 20yr tenure.
  establishedSince: number;
  // Personal quirks assigned to characters so far (charId -> quirk string).
  figureQuirks: Record<string, string>;
}

// Classes are tiered by how they're acquired:
//   common  — soft-gated, anyone can fall into them
//   mid     — capital-gated (wealth/knowledge ease the path)
//   rare    — rite-gated: only a house/guild that holds the rite can grant them
export type CharClass =
  | "commoner"
  | "soldier"
  | "hunter"
  | "knight"
  | "scholar"
  | "merchant"
  | "warden"
  | "stormcaller"
  | "necromancer";

// The rare classes — heritable "intellectual property" a dynasty can lose.
export type RareClass = "warden" | "stormcaller" | "necromancer";

export interface Dynasty {
  id: DynastyId;
  name: string;
  founderId: CharId;
  extinctYear: number | null; // set when the last member dies

  // --- Peoples layer (empty string = none; only used when the world defines
  // cultures/races/faiths). A house belongs to a people; its members inherit
  // that people's names, temperament, and faith.
  cultureId: string;
  raceId: string;
  faithId: string;

  // --- Magic / leveling layer (only used when World.magicEnabled) ----------
  wealth: number; // treasury; earned from lands, spent cultivating heirs
  rite: RareClass | null; // a heritable rare class-rite the house can grant
  riteBearerId: CharId | null; // the living master who can pass the rite on
}

// ---------------------------------------------------------------------------
// Invention — persistent codified knowledge with secrecy and leak dynamics.
// The generalisation of Dynasty.rite/riteBearerId, applied to procedurally
// invented craft-secrets instead of hardcoded rare classes. Modeled with a
// leak probability because pre-patent worlds substitute guild secrecy for IP.
// Magic-heavy provinces suppress invention (magic occupies the same niche).
// ---------------------------------------------------------------------------
export type InventionCategory =
  | "metallurgy"
  | "printing"
  | "medicine"
  | "military"
  | "agriculture"
  | "navigation"
  | "architecture"
  | "textiles";

export type InventionId = string;

export interface Invention {
  id: InventionId;
  name: string; // procedurally-named ("Coastborn compass", "Ibiki brasswork")
  category: InventionCategory;
  tier: 1 | 2 | 3; // small / medium / breakthrough — scales mechanical benefit
  inventedYear: number;
  inventorId: CharId;
  inventorDynastyId: DynastyId;
  inventorProvinceId: ProvinceId;

  // Secrecy — the Factor 1 mechanic. spreadTo holds every dynasty that knows the
  // craft; while secret, this stays a single-dynasty set. Leak rolls per tick.
  secret: boolean;
  leakProbBase: number; // 0.02 default; 0.005 if guild-protected; 0.05 if none
  spreadTo: DynastyId[];
  guildProtected: boolean; // set by GUILD_MONOPOLY_CLAIMED, halves leak
  lost: boolean; // last living carrier died without transmission
  lostYear: number | null;
}

// ---------------------------------------------------------------------------
// Geography — provinces with scarcity. Geography gives history a persistent
// grain: carrying capacity caps population, which caps levies and wealth.
// ---------------------------------------------------------------------------
export type Terrain =
  | "meadow" // lush green heartland — the richest farmland
  | "plains"
  | "hills"
  | "forest"
  | "coast"
  | "mountain"
  | "steppe" // arid grassland — grazing, raiders, thin farming
  | "desert" // barely habitable, harsh
  | "swamp" // wetland, disease-prone
  | "jungle"; // lush but hard to clear/farm

export interface Province {
  id: ProvinceId;
  name: string;
  terrain: Terrain;
  fertility: number; // 0..1 base land quality
  coastal: boolean; // plague spreads faster along coasts
  riverConnected: boolean; // plague spreads along rivers
  neighbors: ProvinceId[]; // connectivity graph (for spread + war reach)

  population: number; // abstract pops (statistical tier)
  titleId: TitleId; // the title that controls this province

  // --- Underground layer ---------------------------------------------------
  // Subsurface provinces are underground halls; they use mineralWealth instead
  // of fertility for carrying capacity and are immune to surface spread effects
  // (plague, blight). Tunnel connections to surface provinces let undead raids
  // emerge above ground if the hold falls.
  subsurface: boolean;
  mineralWealth: number; // 0..1; replaces fertility for underground capacity

  // --- Magic / leveling layer (only used when World.magicEnabled) ----------
  // Mana density supports rare classes and raises a region's leveling ceiling;
  // it also makes a province more PERILOUS (dungeons, monsters), and peril is
  // exactly what mints high-level people.
  manaDensity: number; // 0..1

  // --- World catastrophe overlay (written by catastrophe.ts) ---------------
  // blightLevel degrades carrying capacity; zoneFlags gate special behaviours
  // (undead raids, impassability, mana corruption spread).
  // Both are initialised to 0 / [] in seed.ts and mutate over the run.
  blightLevel: number;  // 0..1; 0 = pristine, 1 = fully blighted
  zoneFlags: string[];  // 'dead_zone' | 'undead_heavy' | 'mana_corrupted' | 'blighted'
  // Flavor of the active corruption — drives which psyche distortion and culture
  // traits are amplified. undefined = pristine or unclassified blight.
  corruptionType?: "necrotic" | "void" | "feral";
}

// ---------------------------------------------------------------------------
// Catastrophe queue — pending chain steps stored on the World. Kept here (not
// in catastrophe.ts) so world.ts can hold the queue without a circular import.
// ---------------------------------------------------------------------------
export interface CatastropheQueueItem {
  provinceId: ProvinceId;
  templateId: string;   // which CatastropheTemplate this step belongs to
  stepIndex: number;    // index into that template's steps[]
  fireYear: number;     // the year this step should execute
  data: Record<string, string | number>; // carry state between steps
}

// ---------------------------------------------------------------------------
// Titles + succession law. Law is mutable (REFORM action) — different laws
// produce different flavours of history.
// ---------------------------------------------------------------------------
export type SuccessionLaw =
  | "primogeniture" // eldest legitimate child
  | "gavelkind" // split among children (approximated: heir + claims to siblings)
  | "elective" // realm picks strongest dynast
  | "seniority" // eldest member of the dynasty
  | "clan_elder"; // eldest of the founding bloodline only; outsiders can never inherit

export type Tier = "county" | "duchy" | "kingdom";

export interface Title {
  id: TitleId;
  name: string;
  tier: Tier;
  law: SuccessionLaw;
  holderId: CharId | null;
  provinceId: ProvinceId; // seat / primary province
  liegeId: TitleId | null; // feudal superior (duchy over county, etc.)
}

// ---------------------------------------------------------------------------
// Goals + schemes — the intentional layer. A goal always has an OBSTACLE;
// the obstacle is what makes it a story. Blocked goals spawn schemes.
// ---------------------------------------------------------------------------
export type GoalType =
  | "SEIZE_TITLE" // press a claim
  | "ELIMINATE_RIVAL" // one person blocks many goals
  | "MARRY" // secure an heir / alliance
  | "EXPAND" // take a neighbouring province
  | "REVENGE" // act on a grudge
  | "REFORM_LAW"; // change succession law in your favour

export interface Goal {
  id: string;
  actorId: CharId;
  type: GoalType;
  targetTitleId: TitleId | null;
  targetCharId: CharId | null; // the obstacle, when it's a person
  priority: number; // 0..1, drives which goals turn into action
}

export type SchemeType = "MURDER" | "USURP" | "REFORM";

export interface Scheme {
  id: string;
  type: SchemeType;
  ownerId: CharId;
  targetCharId: CharId | null;
  targetTitleId: TitleId | null;
  conspirators: CharId[]; // more power, but leaks faster
  progress: number; // 0..1, advances each tick
  secrecy: number; // 0..1, erodes as conspirators join / time passes
  discovered: boolean;
  startYear: number;
}

// ---------------------------------------------------------------------------
// Events — the canonical log. The sifter reads THIS to find storyworthy
// shapes; the renderer turns selected events into prose. Everything that
// happens must leave a structured trace here.
// ---------------------------------------------------------------------------
export type EventType =
  | "BIRTH"
  | "DEATH"
  | "MARRIAGE"
  | "SUCCESSION"
  | "SUCCESSION_CRISIS"
  | "WAR"
  | "SCHEME_HATCHED"
  | "SCHEME_DISCOVERED"
  | "MURDER"
  | "USURP"
  | "REFORM"
  | "FAMINE"
  | "PLAGUE"
  | "HARVEST_FAILURE"
  | "DYNASTY_EXTINCT"
  | "LOWBORN_RISE"
  | "GRUDGE_FORMED"
  // --- Deep past ---
  | "LEGEND" // a mythic prehistory event (foundings, golden ages, cataclysms)
  // --- Magic / leveling layer ---
  | "CLASS_GAINED" // gained a rare, rite-gated class
  | "LEVELED" // crossed a milestone level / became the mightiest of the age
  | "HEIR_TEMPERED" // a house forged an heir in real peril and they grew
  | "ART_LOST" // a rare class-rite died un-transmitted with its last master
  | "HERO_RISEN" // a low-born striver broke through to the heroic tier
  // --- World catastrophe layer ---
  | "BLIGHT_SPREADS"    // first sign: land begins to dry and die
  | "BLIGHT_DEEPENS"    // second stage: terrain shifts, population flees
  | "BLIGHT_LOCKED"     // final stage: province permanently blighted
  | "PORTAL_OPENS"      // dimensional rift: displaced people materialise
  | "MASS_DEATH"        // the displaced die — wrong season, wrong world
  | "DEAD_ZONE_FORMS"   // the dead rise; province becomes an undead no-go zone
  | "UNDEAD_RAID"       // raid erupting from a dead zone onto a neighbour
  | "RITUAL_GONE_WRONG" // a mana-working spirals out of control
  | "MANA_RUPTURE"      // province devastated; mana spikes wildly
  | "CORRUPTION_SPREADS" // mana corruption bleeds into neighbouring provinces
  // --- Underground / dwarf layer ---
  | "DELVED_TOO_DEEP"   // a subsurface hold breaches something ancient; the hold falls to the undead
  // --- Perception / madness layer ---
  | "MADNESS_ONSET"    // a character develops a structured psychological distortion
  // --- Diplomacy layer ---
  | "TRUCE"            // cease-fire minted after war
  | "ALLIANCE_FORMED"  // defensive pact formed between two rulers
  | "TRUCE_BROKEN"     // a paranoid/conqueror_confident ruler breaks the truce early
  | "ALLIANCE_BETRAYED" // a ruler attacks their own ally
  // --- Cultural evolution layer ---
  | "CULTURAL_CONTESTED" // a trait crossed the pressure threshold — generational contest begins
  | "CULTURAL_RIFT"      // elite and folk tiers hold directly opposed traits
  | "CULTURAL_SHIFT"     // a trait established/abandoned in one or both tiers, or aesthetic drift
  // --- Natural disaster layer ---
  | "ERUPTION"           // volcanic eruption at a mountain province — ash cloud follows
  | "ASH_SUMMER"         // harvest failure from volcanic ash; fires globally 2-3 years after ERUPTION
  | "DROUGHT"            // multi-year water shortage spreading through dry-terrain provinces
  | "LOCUST_SWARM"       // crop-destroying insect swarm sweeping fertile-terrain provinces
  // --- Emergent hero/faction layer (state-conditional emergence) ---
  | "ARCHMAGE_EMERGES"       // world's highest-level mage in a high-mana province
  | "DARK_PROPHET_RISES"     // charismatic figure preaches in blighted/pious province
  | "WARLORD_ASCENDANT"      // martial character consolidates power outside titles
  | "LONE_GENIUS_EMERGES"    // solo breakthrough in isolated province, no institution
  | "PARIAH_TURNS_CHAMPION"  // scorned lowborn with grudges becomes powerful
  | "FALLEN_NOBLE_RISES"     // remnant of an extinct dynasty reclaims relevance
  // --- Class & art layer (arts lost, regained, stolen, transformed) ---
  | "ART_REDISCOVERED"       // a scholar recovers a lost art in the culture that lost it
  | "LOST_CLASS_RESURFACES"  // a class not seen for generations reappears
  | "FORBIDDEN_ART_PRACTICED" // dark art wielded openly in a corrupted province
  | "LEGENDARY_SKILL_MANIFESTS" // unique skill awakens in a near-death survivor
  | "CLASS_LINEAGE_BROKEN"   // final capable bearer of a rite dies; art will lapse
  | "RITE_STOLEN"            // a scheme transfers a rite between dynasties
  // --- Trade & asymmetric relations layer ---
  | "TRADE_ROUTE_ESTABLISHED" // durable exchange between two provinces (directional strength)
  | "TRADE_ROUTE_DISRUPTED"  // war/plague/famine breaks an established route
  | "TRIBUTE_IMPOSED"        // stronger title extracts wealth from weaker neighbor
  | "TRIBUTE_REVOKED"        // subordinate outgrows master; tribute lapses
  | "VASSAL_REBELS"          // long-tributary province throws off the yoke by force
  | "MARKET_MONOPOLY"        // one province becomes the dominant trade hub of a cluster
  // --- Class-composition driven layer ---
  | "SCHOLAR_FLOURISH"       // 3+ scholars concentrate in a province
  | "LIBRARY_FOUNDED"        // scholars + a wealthy ruling house build a lasting institution
  | "LIBRARY_BURNED"         // war or blight destroys a founded library
  | "MARTIAL_DECADENCE"      // long peace + no martial characters in a wealthy province
  | "MERCANTILE_ASCENDANT"   // merchants dominate a province's politics
  | "KNOWLEDGE_LOST"         // scholars vanish from a province that had a tradition
  // --- Challenges layer (discrete opportunities for high-risk growth) ---
  | "CHALLENGE_SPAWNED"      // a dragon, wraith host, abyssal gate etc. appears
  | "CHALLENGE_ATTEMPTED"    // a named figure tries their strength against it
  | "CHALLENGE_VANQUISHED"   // and defeats it — a hero is made
  | "CHALLENGE_SLAYS_CHALLENGER" // or is defeated by it — the challenge remains
  | "SKILL_LEARNED_FROM_TRIAL"   // unique named skill earned by beating a hard trial
  | "CLASS_UNLOCKED_BY_TRIAL"    // a class gained by trial, outside the rite path
  // --- Fate / doom / legend layer ---
  | "PROPHECY_UTTERED"       // a prophet foretells a specific doom for a target
  | "PROPHECY_FULFILLED"     // the target died in the way the prophet said
  | "PROPHECY_DEFIED"        // the target died in a way that made a mockery of it
  | "DOOM_LAID"              // a wronged party's kin curses the wrongdoer
  | "DOOM_FULFILLED"         // the doom-cursed comes to a violent end
  | "LEGEND_INSCRIBED"       // a figure's deeds pass into cultural memory
  | "LEGEND_INVOKED"         // a later character calls upon the legend's name
  // --- Culture-driven events (specs/culture-events.ts) ---
  | "SLAVE_REVOLT"           // slavery culture + LOWBORN_RISE or high blight
  | "CASTE_UPRISING"         // caste_rigid + long peace + high pop
  | "MERITOCRATIC_REFORM"    // meritocracy establishes + REFORM follows
  | "PRINTING_PRESS"         // literacy_valued + SCHOLAR_FLOURISH + year>100
  | "TREATISE_PUBLISHED"     // literacy_valued + high-level scholar dies
  | "CRUSADE_CALLED"         // zealous_faith + different-faith neighbour
  | "HERESY_TRIAL"           // zealous_faith + contested against that trait
  | "GUILD_CHARTERED"        // mercantile + MERCANTILE_ASCENDANT + wealth
  | "MERCHANT_PRINCE_RISES"  // mercantile + level-12+ merchant character
  | "CULTURE_SCHISM"         // CULTURAL_RIFT persists 30+ years
  | "CULTURE_MERGED"         // sustained contact + trait overlap
  | "SYNCRETIC_FAITH_BORN"   // two zealous_faith cultures merge
  | "CASTE_FLUIDITY_LOST"    // high stratification for 20+ years
  | "SLAVE_LIBERATION"       // slavery abandoned via CULTURAL_SHIFT
  | "POLYMATH_EMERGES"       // meritocracy + literacy_valued + multi-skilled figure
  // --- Maritime events (specs/maritime-events.ts) ---
  | "SEA_STORM"              // ambient at coastal, pop damage
  | "TSUNAMI"                // reactive from ERUPTION at coastal-adjacent
  | "PIRATE_RAID"            // ambient at coastal, scales with trade routes
  | "WHALING_BOOM"           // coastal windfall — pop + wealth
  | "FISHERY_COLLAPSE"       // ambient at coastal, reactive to WHALING/STORM
  | "NEW_LANDS_DISCOVERED"   // coastal + explorer temperament
  | "NAVAL_BATTLE"           // WAR at coastal-vs-coastal
  | "SHIPWRECK"              // reactive to SEA_STORM
  | "PLAGUE_SHIP"            // PLAGUE at trade partner jumps via sea
  | "TRADING_COMPANY_FORMS"  // MARKET_MONOPOLY + mercantile + 40+y
  | "LIGHTHOUSE_BUILT"       // port + wealthy scholar/merchant
  | "NAVIGATION_CHART_MADE"  // port + literacy_valued
  | "SEA_MONSTER_SPOTTED"    // coastal + high mana
  | "ISLAND_COLONY_FOUNDED"  // after NEW_LANDS_DISCOVERED
  | "SIREN_LURE"             // coastal + high mana kills martial challenger
  // --- Faction events (specs/faction-events.ts) ---
  | "KNIGHTLY_ORDER_FOUNDED" // warrior culture + multiple knights
  | "THIEVES_GUILD_FORMS"    // repeat murders in a wealthy province spawn organised crime
  | "MERCHANT_LEAGUE_FORMED" // trade-route hub with multiple sea routes
  | "HERETIC_MOVEMENT"       // zealous_faith contested internally
  | "ROYAL_INQUISITION"      // heresy trial escalates into standing office
  | "MASONS_GUILD_CHARTERED" // library founded + literacy_valued establishes builders
  | "ADVENTURERS_GUILD_HALL" // multiple challenges vanquished at same province
  | "MERCENARY_COMPANY_RAISED" // war + wealth spawns a for-hire army
  | "BANDIT_KING_RISES"      // vacant title + high pop + no war + ambitious warrior
  | "ASSASSINS_LODGE_FOUNDED" // repeat kinslayings in one dynasty
  | "PIRATE_CONFEDERATION"   // multiple pirate raids consolidate into a fleet
  | "WITCHCOVEN_FORMS"       // high mana + no zealous_faith + necromancer/stormcaller
  // --- Urban / festival / civic events (specs/urban-events.ts) ---
  | "MARKETPLACE_RIOT"       // famine or high pop + no ruler
  | "FESTIVAL_HELD"          // stable ruler + no famine/plague for 10y
  | "ROYAL_TOUR"             // kingdom-tier holder + old age + no war
  | "GRAND_FAIR"             // market monopoly aftermath
  | "PLAGUE_QUARANTINE"      // plague at coastal + literacy_valued + wealthy holder
  | "PUBLIC_WORKS_BEGUN"     // guild + wealth + long peace
  | "TAX_REVOLT"             // caste_rigid or slavery + high wealth extraction
  | "GRAND_TOURNAMENT"       // knightly order + peace + kingdom holder
  | "MAY_DAY_PARADE"         // mercantile + peace + coastal
  | "STREET_PROPHET"         // dark prophet events + high pop
  | "ARCHITECT_APPRENTICED"  // masons guild + scholar
  | "CIVIC_FEUD"             // rival houses in same province + murder
  // --- Religious / miracle events (specs/religious-events.ts) ---
  | "MIRACLE_WITNESSED"      // high piety + zealous_faith culture
  | "SAINT_CANONIZED"        // legend inscribed + zealous_faith + 30y+ old
  | "PILGRIMAGE_ROUTE_OPENED" // saint canonized + trade route
  | "FALSE_PROPHET_UNMASKED" // dark prophet + inquisition
  | "RELIC_UNEARTHED"        // ancient tomb vanquished + zealous_faith
  | "TEMPLE_BUILT"           // wealth + zealous_faith + long peace
  | "HOLY_WAR_DECLARED"      // crusade called + kingdom-tier + strong martial
  | "SACRED_GROVE_RECOGNIZED" // high mana + forest terrain + zealous_faith absent
  | "SCHISM_HEALED"          // syncretic faith + generations of peace
  | "APOSTASY_MOMENT"        // ruler abandons the faith
  | "MONASTIC_ORDER_FOUNDED" // temple built + scholars
  | "FAITH_MARTYRED"         // holy war + priest character dies violently
  // --- Lost peoples of Earth (specs/lost-peoples-events.ts) ---
  // Groups from pre-medieval to medieval Earth history arrive with no
  // memory of Earth. Each event spawns a new dynasty with themed founders,
  // classes, and drives. Once per world per group — Rome fell once, and
  // Rome arrives in Matlu once.
  | "LOST_ROMAN_LEGION"      // legionnaires — disciplined soldiers, Latin names
  | "LOST_VIKING_EXPEDITION" // longship raiders — coastal, greedy, martial
  | "LOST_MONGOL_TUMEN"      // horse archers — steppe, high ambition, hunter/soldier
  | "LOST_GREEK_HOPLITES"    // phalanx warriors — soldiers, honor_bound
  | "LOST_EGYPTIAN_PRIESTHOOD" // priest caste — scholars, high piety
  | "LOST_CELTIC_WARBAND"    // iron-age warriors — forest, hunter/soldier, vengeance
  | "LOST_SAMURAI_RETINUE"   // feudal knights — extreme honor_bound
  | "LOST_BYZANTINE_CATAPHRACTS" // heavy cavalry — knights, doctrinal bias
  | "LOST_PERSIAN_IMMORTALS" // elite guard — soldiers, loyalty above all
  | "LOST_CARTHAGINIAN_FLEET" // merchant fleet — coastal, mercantile, greedy
  | "LOST_NORMAN_KNIGHTS"    // feudal cavalry — knights, ambitious
  | "LOST_HAN_EXPEDITION"    // classical Chinese — scholars + soldiers, literate
  // --- Succession legitimacy (specs/succession-legitimacy.ts) ---
  | "BASTARD_ACKNOWLEDGED"   // ruler recognizes a natural child
  | "BASTARD_LEGITIMIZED"    // formal legitimization (William the Conqueror pattern)
  | "SECRET_HEIR_DISCOVERED" // a hidden royal child is revealed
  | "PRETENDER_APPEARS"      // false claimant (Warbeck, false Dmitry)
  | "PRETENDER_UNMASKED"     // and is exposed
  | "CHILD_KING_CROWNED"     // succession with a minor holder
  | "REGENCY_ESTABLISHED"    // regent takes power over a child king
  | "REGENT_USURPS"          // regent seizes the crown outright
  | "KING_INCAPACITATED"     // madness / illness / madness_onset on the throne
  | "ABDICATION"             // ruler voluntarily steps down
  | "FAVORITE_ASCENDS"       // court favorite becomes de facto power
  | "COUP_D_ETAT"            // military coup (distinct from usurpation)
  // --- Omens & celestial signs (specs/omens-events.ts) ---
  | "SOLAR_ECLIPSE"          // rare, interpreted as omen
  | "COMET_APPEARS"          // once-a-generation
  | "AURORA_SIGHTED"         // northern lights in southern sky = portent
  | "BLOOD_MOON"             // lunar eclipse, doom read into it
  | "EARTHQUAKE_TREMORS"     // felt tremor without catastrophe damage
  | "MONSTROUS_BIRTH"        // deformed calf/child, folk-omen
  | "TWIN_STARS"             // supernova / paired bright stars
  // --- Popular revolts (specs/revolt-events.ts) ---
  | "PEASANT_REVOLT"         // agrarian uprising (Wat Tyler, Jacquerie)
  | "URBAN_MOB_RIOT"         // city crowd, no clear leader
  | "FOOD_RIOT"              // FAMINE + high pop, specifically about bread
  | "MERCHANT_STRIKE"        // guild refuses to trade — economic pressure
  | "TAX_COLLECTOR_LYNCHED"  // rural anger against extraction
  // --- Papal schism / church politics (specs/church-events.ts) ---
  | "ANTIPOPE_ELECTED"       // rival pope claimed (Great Western Schism)
  | "PAPAL_SCHISM"           // formal split of the faith's leadership
  | "COUNCIL_OF_BISHOPS"     // church council convened (Nicaea, Trent)
  | "EXCOMMUNICATION_ISSUED" // formal expulsion from the faith
  | "INTERDICT_LAID"         // a whole region cut off from sacraments
  // --- Family betrayal (specs/betrayal-events.ts) ---
  | "KINSLAYING_NOTORIOUS"   // MURDER within one dynasty becomes generational curse
  | "FRATRICIDE_OPENS_WAR"   // brother kills brother, kingdom splits
  | "OATH_OF_FEALTY_TAKEN"   // formal loyalty pledge
  | "OATH_BROKEN_SACRED"     // sworn oath violated in aggravated way
  | "HOSTAGE_KILLED_TERMS"   // hostage murdered against agreed terms
  | "GUEST_RIGHT_BROKEN"     // sacred host-guest bond violated (Red Wedding)
  | "MENTOR_BETRAYED"        // student turns on their master
  // --- Individual crime & folk-legend (specs/crime-events.ts) ---
  | "SERIAL_KILLER_STALKS"   // repeated MURDERs by one figure creates fear
  | "HIGHWAY_ROBBER_LEGEND"  // Robin Hood analog — the outlaw becomes a name
  | "PIRATE_BLACK_FLAG"      // named pirate captain, distinct from raids
  | "MASS_JAILBREAK"         // dungeon breach in a wealthy province
  | "CROWN_JEWELS_STOLEN"    // symbol-of-power theft
  // --- Concubine & favorite politics (specs/court-events.ts) ---
  | "CONCUBINE_FAVORED"      // ruler takes a low-born favorite
  | "CONCUBINE_BEARS_HEIR"   // Ottoman/Ming pattern — dynastic implications
  | "MISTRESS_INFLUENCES_CROWN" // de Pompadour analog — soft power
  | "EUNUCH_MINISTER_ASCENDS" // gelded court official runs the palace
  | "COURT_INTRIGUE_UNRAVELS"  // shadow-cabinet exposed
  // --- Innovation & personal skill premium (specs/innovation-events.ts) ---
  | "INVENTION_MADE"           // a craftsman codifies a new technique
  | "GUILD_MONOPOLY_CLAIMED"   // mercantile culture formalizes guild exclusivity
  | "INVENTION_LEAKED"         // the secret escapes to another dynasty
  | "RIVAL_REVERSE_ENGINEERS"  // a peer scholar independently reproduces it
  | "INVENTION_LOST"           // last carrier dies, invention passes into legend
  | "INVENTION_REDISCOVERED"   // a later scholar reawakens a lost art
  | "TREATISE_LEAKS_SECRET"    // published treatise inadvertently spreads craft
  | "APPRENTICE_TAKEN"         // master craftsman takes on a student
  | "MASTER_ARTISAN_HONORED"   // personal-mastery path recognised
  | "PATENT_LAW_ADOPTED";      // proto-IP (Venetian statute analog) formalized

export interface WorldEvent {
  id: number;
  year: number;
  type: EventType;
  // Structured participants so the sifter & renderer never parse prose.
  actorId: CharId | null;
  targetId: CharId | null;
  titleId: TitleId | null;
  provinceId: ProvinceId | null;
  // A bag of extra structured facts (counts, names, law names, etc.).
  data: Record<string, string | number | boolean>;
  // Filled in by the sifter, not at creation time.
  significance: number;
}

// ---------------------------------------------------------------------------
// ArcKind — the shape of a story arc. Declared here (not in arcs.ts) so both
// arcs.ts and event-spec.ts can reference it without a circular import.
// ---------------------------------------------------------------------------
export type ArcKind = "title" | "feud" | "dynasty" | "figure" | "calamity" | "culture";

// ---------------------------------------------------------------------------
// Challenge — a discrete, high-risk opportunity for a character to grow. A
// dragon in the mountain, a wraith host in a dead-zone, an abyssal gate.
// Lives on the World as long as it's unvanquished; consumed when a hero beats
// it. Only spawned/attempted under World.magicEnabled — no impact on base sim.
// ---------------------------------------------------------------------------
export interface Challenge {
  id: string;
  provinceId: ProvinceId;
  kind: string;         // e.g. "dragon" | "wraith_host" | "abyssal_gate" — see challenges.ts
  tier: number;         // 1..5 — scales XP reward AND danger
  bornYear: number;
  bornFromEventId: number | null; // if spawned by a catastrophe, that event's id
  vanquishedBy: CharId | null;
  vanquishedYear: number | null;
  unlocksClass: CharClass | null;
  unlocksSkill: string | null;
}
